Repository RaytenCorp/Rayten, pull requests merged in 2024-12, with the labels that each got.

#93 New skill - engineering
  Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Prototypes/Entities/Objects/Misc/implanters.yml
  Resources/Prototypes/Entities/Objects/Specific/atmos.yml
  Resources/Prototypes/Entities/Objects/Tools/tools.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/gravity_generator.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/trinary.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/PA/control_box.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/containment.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/ame.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/portable_generator.yml
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Shuttles/station_anchor.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/air_alarm.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M

#95 Engskills
  Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/botanist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/settings.yml
Labels: Changes: No C#, S: Untriaged, size/M

#96 initial commit
  Content.Server/Vanilla/Skill/AddSkillPointsComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Resources/Changelog/ChangelogVanilla.yml
  Resources/Locale/ru-RU/tips.ftl
  Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/midround.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/botanist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/reporter.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/zookeeper.yml
Labels: Changes: Localization, size/L, S: Untriaged

#98 more fixes
  Resources/Prototypes/Entities/Objects/Specific/Mech/mech_construction.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Recipes/Construction/utilities.yml
Labels: Changes: No C#, S: Untriaged

#101 Перевод крафтов
  Content.Client/Construction/UI/ConstructionMenu.xaml
  Content.Client/Construction/UI/ConstructionMenu.xaml.cs
  Resources/Locale/ru-RU/prototypes/_corvaxnext/entities/clothing/outerclothing/coats.ftl
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/clown_banana.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/clown_hardsuit.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/ducky_slippers.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/glasses_sechud.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/helmet_justice.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/medsec_hud.yml
  Resources/Prototypes/Recipes/Construction/Graphs/clothing/mime_hardsuit.yml
  Resources/Prototypes/Recipes/Construction/clothing.yml
  Resources/Prototypes/Recipes/Construction/fun.yml
  Resources/Prototypes/Recipes/Construction/furniture.yml
  Resources/Prototypes/Recipes/Construction/lighting.yml
  Resources/Prototypes/Recipes/Construction/machines.yml
  Resources/Prototypes/Recipes/Construction/materials.yml
  Resources/Prototypes/Recipes/Construction/modular.yml
  Resources/Prototypes/Recipes/Construction/storage.yml
  Resources/Prototypes/Recipes/Construction/structures.yml
  Resources/Prototypes/Recipes/Construction/tools.yml
  Resources/Prototypes/Recipes/Construction/utilities.yml
  Resources/Prototypes/Recipes/Construction/weapons.yml
  Resources/Prototypes/Recipes/Construction/web.yml
  Resources/Prototypes/Recipes/Crafting/artifact.yml
  Resources/Prototypes/Recipes/Crafting/bots.yml
  Resources/Prototypes/Recipes/Crafting/crates.yml
  Resources/Prototypes/Recipes/Crafting/improvised.yml
  Resources/Prototypes/Recipes/Crafting/potato.yml
  Resources/Prototypes/Recipes/Crafting/smokeables.yml
  Resources/Prototypes/Recipes/Crafting/tallbox.yml
  Resources/Prototypes/Recipes/Crafting/tiles.yml
  Resources/Prototypes/Recipes/Crafting/toys.yml
  Resources/Prototypes/Recipes/Crafting/web.yml
  Resources/Prototypes/Stacks/Materials/Sheets/glass.yml
  Resources/Prototypes/Stacks/Materials/Sheets/metal.yml
  Resources/Prototypes/Stacks/Materials/Sheets/other.yml
  Resources/Prototypes/Stacks/Materials/crystals.yml
  Resources/Prototypes/Stacks/Materials/ingots.yml
  Resources/Prototypes/Stacks/Materials/materials.yml
  Resources/Prototypes/Stacks/Materials/parts.yml
  Resources/Prototypes/Vanilla/Loadouts/Jobs/Command/captain.yml
  Resources/Prototypes/_CorvaxNext/Entities/Clothing/OuterClothing/Coats.yml
  Resources/Textures/_CorvaxNext/Clothing/OuterClothing/Coats/captain_white.rsi/equipped-OUTERCLOTHING-digi.png
  Resources/Textures/_CorvaxNext/Clothing/OuterClothing/Coats/captain_white.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/_CorvaxNext/Clothing/OuterClothing/Coats/captain_white.rsi/icon.png
  Resources/Textures/_CorvaxNext/Clothing/OuterClothing/Coats/captain_white.rsi/inhand-left.png
  Resources/Textures/_CorvaxNext/Clothing/OuterClothing/Coats/captain_white.rsi/inhand-right.png
  Resources/Textures/_CorvaxNext/Clothing/OuterClothing/Coats/captain_white.rsi/meta.json
Labels: Changes: Localization, Changes: Sprites, Changes: UI, Changes: No C#, size/XL, S: Untriaged

#108 Cheap sunglasses hotfix
  Resources/Prototypes/Loadouts/loadout_groups.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#104 Do You Hear Us Captain!?
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/clothing/belt/knightBelt.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/clothing/naval_captain.ftl
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Clothing/Belts/KnightBelt.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Clothing/Shoes/boots.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Clothing/naval_captain.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Melee/power_sabre.yml
  Resources/Prototypes/Vanilla/Loadouts/Jobs/Command/captain.yml
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/belt.png
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/equipped-BELT.png
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/sabre-layer.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/equipped-HELMET-hamster.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/equipped-HELMET.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/inhand-left.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/inhand-right.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/equipped-BACKPACK.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/inhand-left.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/inhand-right.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/off-inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/off-inhand-right.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/on-inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/on-inhand-right.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/powersabre_nocell.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/powersabre_off.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/powersabre_on.png
Labels: Changes: Localization, Changes: Sprites, Changes: No C#

#111 Revert "Specforces (#85)"
  Content.Client/Entry/EntryPoint.cs
  Content.IntegrationTests/Tests/Vanilla/SpecForceTest.cs
  Content.Server/Vanilla/Administration/Commands/CallSpecForcesCommand.cs
  Content.Server/Vanilla/Specforces/SpecForceComponent.cs
  Content.Server/Vanilla/Specforces/SpecForceTeamPrototype.cs
  Content.Server/Vanilla/Specforces/SpecForcesSystem.cs
  Content.Shared/Vanilla/CCVars/CCVarsVanilla.cs
  Resources/Locale/ru-RU/vanilla/ghost/roles/SpecForces.ftl
  Resources/Maps/Shuttles/dart.yml
  Resources/Maps/Vanilla/M0-R.yml
  Resources/Prototypes/Corvax/Markers/Spawners/ert.yml
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/spawners.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/spawners/specforcespawners.ftl
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/spawners/specforcespawners.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/CBURN.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/Death_Squad.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/ERT.yml
  Resources/Prototypes/Vanilla/Roles/specforces.yml
  Resources/Prototypes/_CorvaxNext/Entities/Effects/footstep.yml
  Resources/VanillaStation.lnk
Labels: Changes: Map, Changes: Localization, size/XL, S: Untriaged

#113 добавлен звук при отсутствии навыка
  Content.Shared/Vanilla/CCVars/CCVarsVanilla.cs
  Resources/Audio/Vanilla/SkillSystem/attributions.yml
  Resources/Audio/Vanilla/SkillSystem/meep-merp.ogg
  Resources/Changelog/ChangelogVanilla.yml
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Prototypes/Corvax/Maps/origin.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml
  Resources/Prototypes/Maps/gate.yml
  Resources/Prototypes/Maps/loop.yml
  Resources/VanillaStation.lnk
Labels: Changes: Map, Changes: Localization, Changes: No C#, S: Untriaged, size/S, Changes: Audio
