Repository RaytenCorp/Rayten, pull requests merged in 2024-10, with the labels that each got.

#49 Лисий хвост (Черта внешности)
  Resources/Locale/ru-RU/vanilla/markings/fox.ftl
  Resources/Prototypes/Vanilla/Entities/Mobs/Customization/Markings/fox_parts.yml
  Resources/Textures/Vanilla/Mobs/Customization/human_fox_parts.rsi/meta.json
  Resources/Textures/Vanilla/Mobs/Customization/human_fox_parts.rsi/tail_human_fox_inner_waggin.png
  Resources/Textures/Vanilla/Mobs/Customization/human_fox_parts.rsi/tail_human_fox_waggin.png
Labels: Changes: Localization, No C#, Changes: Sprites, Status: Needs Review

#55 Upstream sync
  Resources/Changelog/ChangelogSyndie.yml
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/junk-airlock-1.png
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/junk-airlock-2.png
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/junk-camera.png
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/junk-canister-1.png
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/junk-firelock-1.png
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/junk-firelock-2.png
  Resources/Textures/Objects/Materials/Scrap/generic.rsi/meta.json
Labels: No C#, Changes: Sprites

#59 Cluster baby
  Content.Benchmarks/MapLoadBenchmark.cs
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Maps/cluster.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/NPCs/silicon.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/cluster.yml
Labels: Changes: Map

#61 chem med skill update
  Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/Medical/cryo_pod.yml
Labels: Changes: Localization
