Repository RaytenCorp/Rayten, pull requests merged in 2024-09, with the labels that each got.

#34 Upstream sync
  Resources/Prototypes/Corvax/Maps/Pools/corvax.yml
  Resources/Prototypes/Corvax/Maps/Pools/default.yml
  Resources/Textures/Clothing/Head/Hoods/chaplain.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hoods/chaplain.rsi/icon.png
  Resources/Textures/Clothing/Head/Hoods/chaplain.rsi/meta.json
  Resources/Textures/Clothing/Head/Hoods/cult.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hoods/cult.rsi/icon.png
  Resources/Textures/Clothing/Head/Hoods/cult.rsi/meta.json
  Resources/Textures/Clothing/Head/Hoods/nun.rsi/equipped-HELMET.png
  Resources/Textures/Clothing/Head/Hoods/nun.rsi/icon.png
  Resources/Textures/Clothing/Head/Hoods/nun.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Misc/cultrobes.rsi/equipped-OUTERCLOTHING-reptilian.png
  Resources/Textures/Clothing/OuterClothing/Misc/cultrobes.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Misc/cultrobes.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Misc/cultrobes.rsi/meta.json
  Resources/Textures/Clothing/OuterClothing/Misc/nunrobe.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Clothing/OuterClothing/Misc/nunrobe.rsi/icon.png
  Resources/Textures/Clothing/OuterClothing/Misc/nunrobe.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpskirt/chaplain.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/chaplain.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/chaplain.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpskirt/chaplain.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/equipped-INNERCLOTHING-reptilian.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/inhand-left.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/inhand-right.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/chaplain.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_dark.rsi/equipped-INNERCLOTHING-reptilian.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_dark.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_dark.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_dark.rsi/meta.json
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_light.rsi/equipped-INNERCLOTHING-reptilian.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_light.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_light.rsi/icon.png
  Resources/Textures/Clothing/Uniforms/Jumpsuit/monastic_robe_light.rsi/meta.json
Labels: Changes: Map, No C#, Changes: Sprites

#37 added cdn
  .github/workflows/publish.yml
  Resources/Changelog/ChangelogVanilla.yml
  Tools/publish_github_artifact.py
Labels: No C#

#38 Somefixes
  .github/workflows/publish-publish.yml
  .github/workflows/publish.yml
  Content.Server/Discord/Webhooks/WebhookBans.cs
  Resources/Audio/Machines/attributions.yml
  Resources/Prototypes/Corvax/Maps/astra.yml
  Resources/Prototypes/Corvax/Maps/avrite.yml
  Resources/Prototypes/Corvax/Maps/delta.yml
  Resources/Prototypes/Corvax/Maps/gelta.yml
  Resources/Prototypes/Corvax/Maps/ishimura.yml
  Resources/Prototypes/Corvax/Maps/maus.yml
  Resources/Prototypes/Corvax/Maps/outpost.yml
  Resources/Prototypes/Corvax/Maps/paper.yml
  Resources/Prototypes/Corvax/Maps/pearl.yml
  Resources/Prototypes/Corvax/Maps/pilgrim.yml
  Resources/Prototypes/Corvax/Maps/silly.yml
  Resources/Prototypes/Corvax/Maps/split.yml
  Resources/Prototypes/Corvax/Maps/terra.yml
  Resources/Prototypes/Corvax/Maps/tushkan.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
  Resources/Prototypes/Corvax/lobbyscreens.yml
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/cog.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/lobbyscreens.yml
  Resources/Textures/Corvax/LobbyScreens/attributions.yml
  Resources/Textures/Corvax/LobbyScreens/silly-island.png
  Resources/Textures/Corvax/LobbyScreens/silly-island.png.yml
Labels: Changes: Map, No C#

#40 Добавлена игрушка ОЦК + ченжлог
  Resources/Changelog/ChangelogVanilla.yml
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/fun/toys.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/plushie_centcom_alia_zimova.png
Labels: Changes: Localization, No C#, Changes: Sprites

#41 Vanilla sponsor loadout's
  Resources/Audio/Vanilla/Items/Toys/attributions.yml
  Resources/Audio/Vanilla/Items/Toys/yooooo.ogg
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/fun/toys.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
  Resources/Locale/ru-RU/vanilla/preferences/loadout-groups.ftl
  Resources/Prototypes/Entities/Objects/Fun/toys.yml
  Resources/Prototypes/Loadouts/Jobs/Security/detective.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/Vanilla/Loadouts/Miscellaneous/legends.yml
  Resources/Prototypes/Vanilla/Loadouts/loadout_groups.yml
  Resources/Textures/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/Objects/Fun/toys.rsi/plushie_una_Akvanova.png
Labels: Changes: Localization, No C#, Changes: Sprites

#44 added super-duper captain sabre
  Resources/Audio/Vanilla/Weapons/attributions.yml
  Resources/Audio/Vanilla/Weapons/powersabrehit.ogg
  Resources/Audio/Vanilla/Weapons/powersabreoff.ogg
  Resources/Locale/ru-RU/vanilla/preferences/loadout-groups.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/melee/sword.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Melee/power_sabre.yml
  Resources/Prototypes/Vanilla/Loadouts/Jobs/Command/captain.yml
  Resources/Prototypes/Vanilla/Loadouts/loadout_groups.yml
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/off-inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/off-inhand-right.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/on-inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/on-inhand-right.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/powersabre_nocell.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/powersabre_off.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/powersabre_on.png
Labels: Changes: Localization, No C#, Changes: Sprites

#48 Фикс неудобного размера менюшки
  Content.Client/Administration/UI/AdminMenuWindow.xaml.cs
Labels: Changes: UI, Status: Needs Review
