Repository RaytenCorp/Rayten, pull requests merged in 2024-11, with the labels that each got.

#65 добавлен новый скилл приборостроение
  Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/books.ftl
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
  Resources/Prototypes/Entities/Mobs/Player/human.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Entities/Mobs/Player/observer.yml
  Resources/Prototypes/Entities/Mobs/Player/replay_observer.yml
  Resources/Prototypes/Entities/Objects/Misc/books.yml
  Resources/Prototypes/Entities/Objects/Power/powercells.yml
  Resources/Prototypes/Entities/Objects/Specific/Robotics/endoskeleton.yml
  Resources/Prototypes/Entities/Structures/Machines/frame.yml
  Resources/Prototypes/Entities/Structures/Power/apc.yml
  Resources/Prototypes/Entities/Structures/Power/substation.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/air_alarm.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/station_map.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/midround.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Recipes/Construction/Graphs/machines/computer.yml
  Resources/Prototypes/Recipes/Construction/Graphs/machines/machine.yml
  Resources/Prototypes/Recipes/Construction/clothing.yml
  Resources/Prototypes/Recipes/Construction/machines.yml
  Resources/Prototypes/Recipes/Construction/modular.yml
  Resources/Prototypes/Recipes/Construction/structures.yml
  Resources/Prototypes/Recipes/Construction/tools.yml
  Resources/Prototypes/Recipes/Construction/utilities.yml
  Resources/Prototypes/Recipes/Crafting/bots.yml
  Resources/Prototypes/Recipes/Crafting/crates.yml
  Resources/Prototypes/Recipes/Crafting/improvised.yml
  Resources/Prototypes/Recipes/Crafting/potato.yml
  Resources/Prototypes/Recipes/Crafting/tallbox.yml
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Roles/Jobs/Science/borg.yml
  Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
Labels: Changes: Localization

#71 Power sabre fix
  Resources/Audio/Vanilla/Weapons/powersabrehit.ogg
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Melee/power_sabre.yml
  Resources/Textures/Vanilla/Objects/Weapons/Melee/powersabre.rsi/on-inhand-right.png
Labels: No C#, Changes: Sprites

#73 new skill
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_assembly.yml
  Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
  Resources/Prototypes/Entities/Structures/Doors/Firelocks/firelock.yml
  Resources/Prototypes/Entities/Structures/Doors/Firelocks/frame.yml
  Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
  Resources/Prototypes/Entities/Structures/Doors/SecretDoor/secret_door.yml
  Resources/Prototypes/Entities/Structures/Doors/Shutter/blast_door.yml
  Resources/Prototypes/Entities/Structures/Doors/Shutter/shutters.yml
  Resources/Prototypes/Entities/Structures/Doors/Windoors/assembly.yml
  Resources/Prototypes/Entities/Structures/Doors/Windoors/base_structurewindoors.yml
  Resources/Prototypes/Entities/Structures/Walls/girders.yml
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
  Resources/Prototypes/Entities/Structures/Windows/mining.yml
  Resources/Prototypes/Entities/Structures/Windows/plasma.yml
  Resources/Prototypes/Entities/Structures/Windows/plastitanium.yml
  Resources/Prototypes/Entities/Structures/Windows/reinforced.yml
  Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
  Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
  Resources/Prototypes/Entities/Structures/Windows/shuttle.yml
  Resources/Prototypes/Entities/Structures/Windows/uranium.yml
  Resources/Prototypes/Entities/Structures/Windows/window.yml
  Resources/Prototypes/Recipes/Construction/materials.yml
  Resources/Prototypes/Recipes/Construction/structures.yml
Labels: No C#

#60 Unenduring
  Resources/Audio/Vanilla/Effects/Footsteps/death1.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/death2.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/death3.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/death4.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/gear1.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/gear2.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/gear3.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/gear4.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/gear5.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/gear6.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/soldier_voice1.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/soldier_voice2.ogg
  Resources/Audio/Vanilla/Effects/Footsteps/soldier_voice3.ogg
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Jobs/CentComm/cburn.yml
  Resources/Prototypes/Roles/Jobs/CentComm/deathsquad.yml
  Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/Prototypes/Vanilla/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/Vanilla/SoundCollections/footsteps.yml
  Resources/Prototypes/Vanilla/Voice/speech_sounds.yml
Labels: No C#, Status: Needs Review

#81 tradepost update
  .github/workflows/check-crlf.yml
  Resources/Maps/Shuttles/Торговый пост.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Tools/check_crlf.py
Labels: Changes: Map, Changes: No C#, size/XL, S: Untriaged

#76 Ломать Плохое
  Resources/Locale/en-US/vanilla/ghost/roles/ghost-role-component.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/chemicals.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/narcotics.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/physical-desc.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meth.ftl
  Resources/Locale/ru-RU/vanilla/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/consumable/food/bluesky.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/reagents/meta/chemicals.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/reagents/meta/narcotics.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/reagents/meta/physical-desc.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/reagents/meth.ftl
  Resources/Maps/Shuttles/ShuttleEvent/cookers_shuttle.yml
  Resources/Prototypes/Entities/Objects/Tools/flare.yml
  Resources/Prototypes/Entities/Objects/Tools/matches.yml
  Resources/Prototypes/GameRules/unknown_shuttles.yml
  Resources/Prototypes/Resources.lnk
  Resources/Prototypes/Shuttles/shuttle_incoming_event.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/roles.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/spawners.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Consumable/Food/BlueSky.yml
  Resources/Prototypes/Vanilla/Reagents/BreakingBad.yml
  Resources/Prototypes/Vanilla/Recipes/Cooking/BlueSkyRecipe.yml
  Resources/Prototypes/Vanilla/Recipes/Reactions/BreakingBad.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/Fun/cookers.yml
  Resources/Textures/Vanilla/Objects/Consumable/Food/BlueSky.rsi/BlueSkyPiece.png
  Resources/Textures/Vanilla/Objects/Consumable/Food/BlueSky.rsi/BlueSkyPlate.png
  Resources/Textures/Vanilla/Objects/Consumable/Food/BlueSky.rsi/meta.json
  Resources/VanillaStation.lnk
Labels: Changes: Map, Changes: Localization, No C#, Changes: Sprites, Changes: No C#, size/XL, S: Needs Review

#82 крутые звуки для офицеров СБ
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: Changes: No C#, S: Untriaged, size/M

#84 фикс навыков варщиков
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/roles.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/settings.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Consumable/Food/BlueSky.yml
  Resources/Prototypes/Vanilla/Reagents/BreakingBad.yml
  Resources/Prototypes/Vanilla/Recipes/Cooking/BlueSkyRecipe.yml
  Resources/Prototypes/Vanilla/Recipes/Reactions/BreakingBad.yml
Labels: Changes: No C#, S: Untriaged, size/M

#85 Specforces
  Content.Client/Entry/EntryPoint.cs
  Content.IntegrationTests/Tests/Vanilla/SpecForceTest.cs
  Content.Server/Vanilla/Administration/Commands/CallSpecForcesCommand.cs
  Content.Server/Vanilla/Specforces/SpecForceComponent.cs
  Content.Server/Vanilla/Specforces/SpecForceTeamPrototype.cs
  Content.Server/Vanilla/Specforces/SpecForcesSystem.cs
  Content.Shared/Vanilla/CCVars/CCVarsVanilla.cs
  Resources/Locale/ru-RU/vanilla/ghost/roles/SpecForces.ftl
  Resources/Maps/Shuttles/dart.yml
  Resources/Prototypes/Corvax/Markers/Spawners/ert.yml
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Roles/Jobs/CentComm/emergencyresponseteam.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/unknownshuttlespawners.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/spawners/specforcespawners.ftl
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/spawners/specforcespawners.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/CBURN.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/Death_Squad.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/ERT.yml
  Resources/Prototypes/Vanilla/Roles/specforces.yml
  Resources/Prototypes/_CorvaxNext/Entities/Effects/footstep.yml
  Resources/VanillaStation.lnk
Labels: Changes: Map, Changes: Localization, size/XL

#88 Captains DRIP
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/clothing/belt/belts.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/clothing/hands/gloves.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/clothing/head/hats.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/structures/machines/vending_machines.ftl
  Resources/Locale/ru-RU/vanilla/preferences/loadout-groups.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/dressers.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Loadouts/Jobs/Command/captain.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Vanilla/Loadouts/Jobs/Command/captain.yml
  Resources/Prototypes/Vanilla/Loadouts/loadout_groups.yml
  Resources/Prototypes/_CorvaxNext/Catalog/VendingMachines/Inventories/CaptainDrobeInventory.yml
  Resources/Prototypes/_CorvaxNext/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/_CorvaxNext/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/_CorvaxNext/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/_CorvaxNext/Entities/Clothing/Uniforms/jumpsuits.yml
  Resources/Prototypes/_CorvaxNext/Entities/Structures/Machines/vending_machines.yml
  Resources/Textures/_CorvaxNext/Structures/Machines/VendingMachines/captaindrobe.rsi/broken.png
  Resources/Textures/_CorvaxNext/Structures/Machines/VendingMachines/captaindrobe.rsi/meta.json
  Resources/Textures/_CorvaxNext/Structures/Machines/VendingMachines/captaindrobe.rsi/normal-unshaded.png
  Resources/Textures/_CorvaxNext/Structures/Machines/VendingMachines/captaindrobe.rsi/off.png
  Resources/Textures/_CorvaxNext/Structures/Machines/VendingMachines/captaindrobe.rsi/panel.png
  Resources/migration.yml
Labels: Changes: Localization, Changes: Sprites, size/L, Changes: No C#, S: Untriaged

#89 new ert shuttle
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/weapons/guns/turrets.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/weapons/melee/sword.ftl
  Resources/Maps/Vanilla/M0-R.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Turrets.yml
  Resources/Prototypes/Vanilla/Roles/Jobs/SpecForces/ERT.yml
  Resources/Prototypes/Vanilla/Roles/specforces.yml
  Resources/Prototypes/ai_factions.yml
Labels: Changes: Map, Changes: Localization, Changes: No C#, S: Untriaged
