Repository RaytenCorp/Rayten, pull requests merged in 2025-03, with the labels that each got.

#169 Респрайты
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Cartons/black.rsi/icon.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Cartons/blue.rsi/icon.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Cartons/green.rsi/icon.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Cartons/mixed.rsi/icon.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Cartons/red.rsi/icon.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/black.rsi/closed.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/black.rsi/open.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/blue.rsi/closed.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/blue.rsi/open.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/green.rsi/closed.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/green.rsi/open.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/mixed.rsi/closed.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/mixed.rsi/open.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/red.rsi/closed.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/red.rsi/open.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/syndicate.rsi/closed.png
  Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/Packs/syndicate.rsi/open.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/advkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/blackkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/brutekit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/burnkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/firstaid.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/o2kit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/radkit.png
  Resources/Textures/Objects/Specific/Medical/firstaidkits.rsi/toxinkit.png
Labels: Changes: Sprites, Changes: No C#, size/XS

#170 skill-patch 0.95.1
  Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillBookComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillLearnerComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillTrainerComponent.cs
Labels: S: Untriaged, size/S

#172 Burokratia
  Resources/Locale/ru-RU/vanilla/prototypes/Bureaucracy/Orders.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Bureaucracy/Reports.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Bureaucracy/Requests.ftl
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Reports.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Requests.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/orders.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M

#178 nukiefix
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/Roles/Antags/nukeops.yml
Labels: Changes: No C#, S: Untriaged

#184 скелет от 10 людей
  Resources/Prototypes/GameRules/events.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#186 somefixes
  Resources/Locale/ru-RU/prototypes/roles/antags.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/hammers.ftl
  Resources/Prototypes/Entities/Mobs/Player/clone.yml
  Resources/Prototypes/GameRules/roundstart.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/S

#180 Добавлены портативные мониторинги
  Resources/Prototypes/Recipes/Lathes/Packs/engineering.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Devices/handheld_monitors.yml
  Resources/Prototypes/Vanilla/Recipes/Lathes/devices.yml
  Resources/Textures/Objects/Specific/Engineering/alerttablet.rsi/alert-0.png
  Resources/Textures/Objects/Specific/Engineering/alerttablet.rsi/alert-1.png
  Resources/Textures/Objects/Specific/Engineering/alerttablet.rsi/alert-2.png
  Resources/Textures/Objects/Specific/Engineering/alerttablet.rsi/meta.json
  Resources/Textures/Objects/Specific/Engineering/alerttablet.rsi/tablet.png
  Resources/Textures/Objects/Specific/Engineering/atmostablet.rsi/generic.png
  Resources/Textures/Objects/Specific/Engineering/atmostablet.rsi/meta.json
  Resources/Textures/Objects/Specific/Engineering/atmostablet.rsi/tablet.png
  Resources/Textures/Objects/Specific/Engineering/powertablet.rsi/generic.png
  Resources/Textures/Objects/Specific/Engineering/powertablet.rsi/meta.json
  Resources/Textures/Objects/Specific/Engineering/powertablet.rsi/tablet.png
Labels: Changes: Sprites, Changes: No C#, S: Needs Review, size/M

#187 Навыки [v0.97]
  Content.Server/Vanilla/Skill/Components/GunTrainerComponent.cs
  Content.Shared/Vanilla/Skill/components/AssComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Resources/Audio/Vanilla/Items/Implants/AssImplant-open.ogg
  Resources/Audio/Vanilla/Items/Implants/attributions.yml
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/pka.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Bow/bow.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/HMGs/hmgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/flare_gun.yml
  Resources/Prototypes/Vanilla/Actions/types.yml
  Resources/Prototypes/Vanilla/Damage/modifier_sets.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Misc/subdermal_implants.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Makeshift/emittergun.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M, size/S, Changes: Audio

#192 somefixes
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/fun/toys.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/nukediscteleport.ftl
  Resources/Prototypes/Entities/Objects/Specific/Security/target.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
  Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/S

#195 клиентское предсказание в навыках
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
Labels: S: Untriaged, size/M

#197 Upstream sync
  Content.Client/Administration/AdminNameOverlay.cs
  Content.Client/Administration/Systems/AdminSystem.Overlay.cs
  Content.Client/Administration/UI/Tabs/PlayerTab/PlayerTab.xaml.cs
  Content.Client/Administration/UI/Tabs/PlayerTab/PlayerTabEntry.xaml
  Content.Client/Administration/UI/Tabs/PlayerTab/PlayerTabEntry.xaml.cs
  Content.Client/Administration/UI/Tabs/PlayerTab/PlayerTabHeader.xaml
  Content.Client/Administration/UI/Tabs/PlayerTab/PlayerTabHeader.xaml.cs
  Content.Client/Options/UI/Tabs/AdminOptionsTab.xaml
  Content.Client/Options/UI/Tabs/AdminOptionsTab.xaml.cs
  Content.IntegrationTests/Tests/Embedding/EmbedTest.cs
  Content.Server/Administration/Systems/AdminSystem.cs
  Content.Server/Administration/Systems/AdminVerbSystem.cs
  Content.Server/NPC/Pathfinding/PathfindingSystem.cs
  Content.Server/Power/Commands/PowerValidateCommand.cs
  Content.Server/Power/EntitySystems/PowerNetSystem.cs
  Content.Server/Power/Pow3r/BatteryRampPegSolver.cs
  Content.Server/Power/Pow3r/IPowerSolver.cs
  Content.Server/Power/Pow3r/NoOpSolver.cs
  Content.Shared/Administration/PlayerInfo.cs
  Content.Shared/CCVar/CCVars.Interface.cs
  Content.Shared/Mind/RoleTypePrototype.cs
  Content.Shared/Projectiles/SharedProjectileSystem.cs
  Content.Shared/Roles/MindRoleComponent.cs
  Content.Shared/Roles/SharedRoleSystem.cs
  Resources/Changelog/Admin.yml
  Resources/ConfigPresets/WizardsDen/vulture.toml
  Resources/Locale/en-US/administration/ui/tabs/player-tab.ftl
  Resources/Locale/en-US/datasets/figurines.ftl
  Resources/Locale/en-US/escape-menu/ui/options-menu.ftl
  Resources/Locale/en-US/power/commands.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/specific/chemistry-bottles.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/weapons/bombs/cumulative_efp.ftl
  Resources/Locale/ru-RU/administration/ui/tabs/player-tab.ftl
  Resources/Locale/ru-RU/datasets/figurines.ftl
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Locale/ru-RU/power/commands.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/bombs/cumulative_efp.ftl
  Resources/Prototypes/Datasets/figurines.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Fun/figurines.yml
  Resources/Prototypes/Entities/Structures/Walls/grille.yml
  Resources/Prototypes/Roles/MindRoles/mind_roles.yml
  Resources/Prototypes/Roles/role_types.yml
  Resources/Textures/Objects/Devices/pda.rsi/id_overlay_wide.png
  Resources/Textures/Objects/Devices/pda.rsi/light_overlay_wide.png
  Resources/Textures/Objects/Devices/pda.rsi/meta.json
Labels: Changes: Localization, Changes: Sprites, Changes: UI

#199 new lobby music
  Resources/Audio/Vanilla/Lobby/Amnesia.ogg
  Resources/Audio/Vanilla/Lobby/Drained.ogg
  Resources/Audio/Vanilla/Lobby/Dust.ogg
  Resources/Audio/Vanilla/Lobby/attributions.yml
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: Changes: No C#, S: Untriaged, Changes: Audio

#200 Somefixes
  .github/workflows/publish.yml
  Resources/Locale/ru-RU/ss14-ru/prototypes/objectives/wizard.ftl
  Resources/Prototypes/Entities/Mobs/Player/skeleton.yml
  Resources/Prototypes/GameRules/subgamemodes.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M
