Repository RaytenCorp/Rayten, pull requests merged in 2025-04, with the labels that each got.

#194 EFP ( C2 )
  Resources/Prototypes/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/Recipes/Lathes/devices.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Devices/handheld_monitors.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Bombs/cumulative_efp.yml
  Resources/Prototypes/Vanilla/Recipes/Lathes/devices.yml
  Resources/Textures/Vanilla/Objects/Specific/Atmos/alerttablet.rsi/alert-0.png
  Resources/Textures/Vanilla/Objects/Specific/Atmos/alerttablet.rsi/alert-1.png
  Resources/Textures/Vanilla/Objects/Specific/Atmos/alerttablet.rsi/alert-2.png
  Resources/Textures/Vanilla/Objects/Specific/Atmos/alerttablet.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Specific/Atmos/alerttablet.rsi/tablet.png
  Resources/Textures/Vanilla/Objects/Specific/Atmos/atmostablet.rsi/generic.png
  Resources/Textures/Vanilla/Objects/Specific/Atmos/atmostablet.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Specific/Atmos/atmostablet.rsi/tablet.png
  Resources/Textures/Vanilla/Objects/Specific/Engineering/powertablet.rsi/generic.png
  Resources/Textures/Vanilla/Objects/Specific/Engineering/powertablet.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Specific/Engineering/powertablet.rsi/tablet.png
  Resources/Textures/Vanilla/Objects/Weapons/Bombs/cumulative_efp.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Weapons/Bombs/cumulative_efp.rsi/inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Bombs/cumulative_efp.rsi/inhand-right.png
  Resources/Textures/Vanilla/Objects/Weapons/Bombs/cumulative_efp.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Weapons/Bombs/cumulative_efp.rsi/primed.png
Labels: Changes: Sprites, Changes: No C#, S: Untriaged, S: Needs Review, size/S

#203 Удаление пассажиров
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml
  Content.Client/Lobby/UI/HumanoidProfileEditor.xaml.cs
  Content.IntegrationTests/Tests/Round/JobTest.cs
  Content.Shared/GameTicking/SharedGameTicker.cs
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
  Resources/Maps/Nonstations/meteor-arena.yml
  Resources/Prototypes/Corvax/Maps/Corvax/astra.yml
  Resources/Prototypes/Corvax/Maps/Corvax/avrite.yml
  Resources/Prototypes/Corvax/Maps/Corvax/awesome.yml
  Resources/Prototypes/Corvax/Maps/Corvax/cute.yml
  Resources/Prototypes/Corvax/Maps/Corvax/delta.yml
  Resources/Prototypes/Corvax/Maps/Corvax/gelta.yml
  Resources/Prototypes/Corvax/Maps/Corvax/glacier.yml
  Resources/Prototypes/Corvax/Maps/Corvax/ishimura.yml
  Resources/Prototypes/Corvax/Maps/Corvax/maus.yml
  Resources/Prototypes/Corvax/Maps/Corvax/outpost.yml
  Resources/Prototypes/Corvax/Maps/Corvax/paper.yml
  Resources/Prototypes/Corvax/Maps/Corvax/pearl.yml
  Resources/Prototypes/Corvax/Maps/Corvax/pilgrim.yml
  Resources/Prototypes/Corvax/Maps/Corvax/silly.yml
  Resources/Prototypes/Corvax/Maps/Corvax/split.yml
  Resources/Prototypes/Corvax/Maps/Corvax/terra.yml
  Resources/Prototypes/Corvax/Maps/Corvax/tushkan.yml
  Resources/Prototypes/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Maps/amber.yml
  Resources/Prototypes/Maps/arenas.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/convex.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/debug.yml
  Resources/Prototypes/Maps/elkridge.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/gate.yml
  Resources/Prototypes/Maps/loop.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/oasis.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/plasma.yml
  Resources/Prototypes/Maps/reach.yml
  Resources/Prototypes/Maps/relic.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Maps/train.yml
  Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
Labels: Changes: Map, Changes: UI, size/M

#208 Trasnslate fix
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/mobs/player/silicon/silicon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/specific/robotics/R1_components.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/specific/robotics/R1_modules.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/weapons/bombs/cumulative_efp.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/weapons/makeshift/bombpack.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/weapons/makeshift/emittergun.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/weapons/makeshift/makeshift_doublebarrel.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/entities/objects/weapons/makeshift/makeshift_plasmasword.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/objectives/R1.ftl
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/Silicon/silicon.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged

#213 background v0.2.0
  Content.Client/Vanilla/Background/BackgroundPrototype.cs
  Content.Server/Vanilla/Background/BackgroundPrototype.cs
  Content.Shared/Vanilla/Background/Components/AwaitBackgroundComponent.cs
  Content.Shared/Vanilla/Background/Components/BackgroundComponent.cs
  Content.Shared/Vanilla/Background/Prototypes/BackgroundGroupPrototype.cs
  Content.Shared/Vanilla/Background/Prototypes/BackgroundPrototype.cs
  Content.Shared/Vanilla/Jammer/SharedJammerSystem.cs
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/roles/mind_roles.ftl
  Resources/Locale/ru-RU/vanilla/ghost/roles/ghost-role-component.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/ghostroles/LoneOpBackgrounds.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/ghostroles/NukeOpsTeam.ftl
  Resources/Locale/ru-RU/vanilla/ui/background.ftl
  Resources/Prototypes/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/Entities/Mobs/Player/skeleton.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/GameRules/roundstart.yml
  Resources/Prototypes/Vanilla/Backgrounds/roles/ghostroles/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/roles/ghostroles/LoneOpBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/roles/ghostroles/NukeOpsTeam.yml
  Resources/Prototypes/Vanilla/Roles/mind_roles.yml
Labels: Changes: Localization, S: Untriaged, size/M

#214 background v0.2.1
  Resources/Locale/ru-RU/vanilla/ui/background.ftl
  Resources/Prototypes/Vanilla/Backgrounds/roles/ghostroles/NukeOpsTeam.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged

#216 Somefixes
  Content.Server/Discord/Webhooks/WebhookBans.cs
  Content.Shared/Vanilla/CCVars/CCVVars.cs
  Content.Shared/Vanilla/Voices/VoiceEmitterComponent.cs
  Content.Shared/Vanilla/Voices/VoicePrototype.cs
  Resources/Audio/Vanilla/Effects/Voices/Alphys.ogg
  Resources/Audio/Vanilla/Effects/Voices/Asgore.ogg
  Resources/Audio/Vanilla/Effects/Voices/Asriel.ogg
  Resources/Audio/Vanilla/Effects/Voices/EvilFlowey.ogg
  Resources/Audio/Vanilla/Effects/Voices/Flowey.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania1.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania2.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania3.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania4.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania5.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania6.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania7.ogg
  Resources/Audio/Vanilla/Effects/Voices/Mettaton.ogg
  Resources/Audio/Vanilla/Effects/Voices/Papyrus.ogg
  Resources/Audio/Vanilla/Effects/Voices/SANS.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie1.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie2.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie3.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie4.ogg
  Resources/Audio/Vanilla/Effects/Voices/Toriel.ogg
  Resources/Audio/Vanilla/Effects/Voices/Undyne.ogg
  Resources/Audio/Vanilla/Effects/Voices/atributions.yml
  Resources/Locale/ru-RU/vanilla/prototypes/DepartmentGoals/EngGoals.ftl
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
  Resources/Prototypes/Corvax/tts-voices.yml
  Resources/Prototypes/Entities/Mobs/base.yml
  Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/base_machineboard.yml
  Resources/Prototypes/Entities/Objects/Devices/Electronics/door.yml
  Resources/Prototypes/Entities/Objects/Devices/Electronics/firelock.yml
  Resources/Prototypes/Entities/Objects/Devices/Electronics/misc.yml
  Resources/Prototypes/Entities/Objects/Devices/Electronics/timer.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Vanilla/SoundCollections/Voices.yml
  Resources/Prototypes/Vanilla/Voices.yml
Labels: Changes: Localization, size/L, S: Untriaged, Changes: Audio

#219 Ванила маппул
  Resources/ConfigPresets/Vanilla/Vanilla.toml
  Resources/Prototypes/Corvax/Maps/Corvax/avrite.yml
  Resources/Prototypes/Corvax/Maps/Corvax/awesome.yml
  Resources/Prototypes/Corvax/Maps/Corvax/delta.yml
  Resources/Prototypes/Corvax/Maps/Corvax/glacier.yml
  Resources/Prototypes/Corvax/Maps/Corvax/maus.yml
  Resources/Prototypes/Corvax/Maps/Corvax/paper.yml
  Resources/Prototypes/Corvax/Maps/Corvax/pearl.yml
  Resources/Prototypes/Corvax/Maps/Corvax/pilgrim.yml
  Resources/Prototypes/Corvax/Maps/Corvax/silly.yml
  Resources/Prototypes/Corvax/Maps/Corvax/terra.yml
  Resources/Prototypes/Corvax/Maps/Corvax/tushkan.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/omega.yml
  Resources/Prototypes/Maps/packed.yml
  Resources/Prototypes/Maps/plasma.yml
  Resources/Prototypes/Maps/reach.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Maps/train.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Makeshift/makeshift_plasmasword.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Melee/plasmasword.yml
  Resources/Prototypes/Vanilla/Maps/Pools/VanillaPool.yml
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/belt.png
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/equipped-BELT.png
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Clothing/Belt/knightBelt.rsi/sabre-layer.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/equipped-HELMET.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/equipped-BACKPACK.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/satchel.rsi/icon.png
Labels: Changes: Map, Changes: Sprites, Changes: No C#, S: Untriaged, size/M

#225 Перестройка системы целей отделов
  Content.Server/Vanilla/DepartmentGoal/DepartmentGoalPrototype.cs
  Resources/Locale/ru-RU/corvax/speech/speech-chatsan.ftl
  Resources/Prototypes/Vanilla/DepartmentGoals/CargoGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/EngGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/MedGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/RnDGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SecGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SrvGoals.yml
Labels: Changes: Localization, S: Untriaged, size/M

#222 Доработки Р-1
  Content.Shared/Vanilla/Fluids/BloodSuckerComponent.cs
  Resources/Prototypes/Vanilla/Actions/R1Actions.yml
  Resources/Prototypes/Vanilla/Actions/R2Coins.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/Silicon/silicon.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Specific/Robotics/R1_modules.yml
  Resources/Textures/Vanilla/Mobs/Silicon/chassis.rsi/R1_Body.png
  Resources/Textures/Vanilla/Mobs/Silicon/chassis.rsi/R1_Dash.png
  Resources/Textures/Vanilla/Mobs/Silicon/chassis.rsi/R1_Enabled.png
  Resources/Textures/Vanilla/Mobs/Silicon/chassis.rsi/R2_Dash.png
  Resources/Textures/Vanilla/Mobs/Silicon/chassis.rsi/meta.json
Labels: Changes: Sprites, S: Untriaged, size/M

#188 Felinid
  Content.Server/Vanilla/Felinid/FelinidAccentComponent.cs
  Content.Server/Vanilla/Felinid/FelinidAccentSystem.cs
  Resources/Locale/en-US/vanilla/Trait/Felinid.ftl
  Resources/Locale/ru-RU/chat/emotes.ftl
  Resources/Locale/ru-RU/datasets/names/cookie_fortune.ftl
  Resources/Locale/ru-RU/datasets/names/first.ftl
  Resources/Locale/ru-RU/datasets/names/first_female.ftl
  Resources/Locale/ru-RU/datasets/names/revenant_adjective.ftl
  Resources/Locale/ru-RU/datasets/names/revenant_theme.ftl
  Resources/Locale/ru-RU/delivery/delivery-spam.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/consumable/food/produce.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/deliveries/deliveries_items.ftl
  Resources/Prototypes/Corvax/Entities/Mobs/Customization/Markings/fox_parts.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/cyberlibs.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/ears.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/gauze.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/tattoos.yml
  Resources/Prototypes/Entities/Mobs/Customization/Markings/undergarments.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Customization/Markings/fox_parts.yml
  Resources/Prototypes/Vanilla/Felinid/TraitsSpeech/CatSpeech.yml
  Resources/Prototypes/Vanilla/Felinid/felinid.yml
  Resources/Prototypes/Vanilla/Felinid/felinidsound/kriks.ogg
  Resources/Prototypes/Vanilla/Felinid/felinidsound/murchanie.ogg
  Resources/Prototypes/Vanilla/Felinid/felinidsound/myaukan.ogg
Labels: Changes: Localization, size/L, S: Untriaged, S: Needs Review, Changes: Audio

#229 end
  Resources/Prototypes/Entities/Objects/Tools/matches.yml
Labels: Changes: No C#, S: Untriaged, size/XS

#233 Upstream sync
  Content.Server/Administration/Commands/AGhostCommand.cs
  Content.Server/Database/ServerDbManager.cs
  Content.Server/Destructible/Thresholds/Behaviors/EmptyAllContainersBehaviour.cs
  Content.Server/Ghost/GhostSystem.cs
  Content.Server/Guardian/GuardianComponent.cs
  Content.Server/Guardian/GuardianSystem.cs
  Content.Server/Mind/MindSystem.cs
  Content.Server/Ninja/Systems/NinjaSuitSystem.cs
  Content.Server/PAI/PAISystem.cs
  Content.Server/Polymorph/Systems/PolymorphSystem.Map.cs
  Content.Server/Polymorph/Systems/PolymorphSystem.cs
  Content.Server/Power/EntitySystems/CableSystem.Placer.cs
  Content.Server/Salvage/SalvageSystem.Expeditions.cs
  Content.Server/Salvage/SpawnSalvageMissionJob.cs
  Content.Server/Worldgen/Systems/WorldgenConfigSystem.cs
  Content.Shared/Bed/Cryostorage/SharedCryostorageSystem.cs
  Content.Shared/Ghost/GhostComponent.cs
  Content.Shared/Ghost/SharedGhostSystem.cs
  Content.Shared/Movement/Components/MovementSpeedModifierComponent.cs
  Content.Shared/PAI/PAIComponent.cs
  Content.Shared/PAI/SharedPAISystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/ss14-ru/prototypes/entities/clothing/back/duffel.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/markers/spawners/random/anomaly.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/markers/spawners/random/shadowkudzu.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/fun/pai.ftl
  Resources/Locale/en-US/store/currency.ftl
  Resources/Locale/en-US/store/pai-catalog.ftl
  Resources/Locale/ru-RU/objectives/conditions/kill-person.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/pai.ftl
  Resources/Locale/ru-RU/store/currency.ftl
  Resources/Locale/ru-RU/store/pai-catalog.ftl
  Resources/Maps/Ruins/hydro_outpost.yml
  Resources/Prototypes/Catalog/pai_catalog.yml
  Resources/Prototypes/Datasets/Names/arachnid.yml
  Resources/Prototypes/Datasets/Names/base_gendered.yml
  Resources/Prototypes/Datasets/Names/clown.yml
  Resources/Prototypes/Datasets/Names/last_female.yml
  Resources/Prototypes/Datasets/Names/last_male.yml
  Resources/Prototypes/Datasets/Names/moth.yml
  Resources/Prototypes/Datasets/Names/ninja.yml
  Resources/Prototypes/Datasets/Names/regalrat.yml
  Resources/Prototypes/Datasets/Names/reptilian_male.yml
  Resources/Prototypes/Datasets/Names/vox.yml
  Resources/Prototypes/Entities/Clothing/Back/duffel.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/anomaly.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/shadowkudzu.yml
  Resources/Prototypes/Entities/Objects/Fun/pai.yml
  Resources/Prototypes/Entities/Stations/base.yml
  Resources/Prototypes/Store/categories.yml
  Resources/Prototypes/Store/currency.yml
Labels: Changes: Map, Changes: Localization, Changes: No C#, S: Untriaged, size/M

#230 Фикс фелинидов
  Resources/Locale/en-US/ss14-ru/prototypes/vanilla/felinid/felinid.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/felinid/felinid.ftl
  Resources/Prototypes/Vanilla/Felinid/felinid.yml
  Resources/Prototypes/Vanilla/Felinid/felinidsound/kriks.ogg
  Resources/Prototypes/Vanilla/Felinid/felinidsound/murchanie.ogg
  Resources/Prototypes/Vanilla/Felinid/felinidsound/myaukan.ogg
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/S, Changes: Audio

#237 Upstream sync
  Content.Client/Disposal/Unit/DisposalUnitSystem.cs
  Content.Client/UserInterface/Systems/Storage/StorageUIController.cs
  Content.Shared/Delivery/SharedDeliverySystem.cs
  Content.Shared/Doors/Components/TurnstileComponent.cs
  Content.Shared/FingerprintReader/FingerprintReaderSystem.cs
  Content.Shared/IdentityManagement/Components/IdentityBlockerComponent.cs
  Content.Shared/Teleportation/Systems/SwapTeleporterSystem.cs
  Content.Shared/Tools/Components/SimpleToolUsageComponent.cs
  Content.Shared/Tools/Systems/SimpleToolUsageSystem.cs
  Resources/Changelog/Changelog.yml
  Resources/Locale/en-US/delivery/delivery-component.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/vanilla/felinid/felinid.ftl
  Resources/Locale/en-US/tools/simple-tool-usage.ftl
  Resources/Locale/ru-RU/access/components/genpop.ftl
  Resources/Locale/ru-RU/delivery/delivery-component.ftl
  Resources/Locale/ru-RU/delivery/delivery-messages.ftl
  Resources/Locale/ru-RU/doors/components/turnstile.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/service.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/random/crates.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/turnstile.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/felinid/felinid.ftl
  Resources/Locale/ru-RU/tools/simple-tool-usage.ftl
  Resources/Maps/amber.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
  Resources/Prototypes/Entities/Mobs/Player/observer.yml
  Resources/Prototypes/Entities/Objects/Deliveries/deliveries.yml
  Resources/Prototypes/Entities/Structures/Doors/turnstile.yml
  Resources/Prototypes/Entities/Structures/Furniture/toilet.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Textures/Structures/Wallmounts/posters.rsi/meta.json
  Resources/Textures/Structures/Wallmounts/posters.rsi/poster36_contraband.png
  Resources/migration.yml
Labels: Changes: Map, Changes: Localization, Changes: Sprites, S: Untriaged

#236 новые голоса
  Resources/Audio/Vanilla/Effects/Voices/Alphys.ogg
  Resources/Audio/Vanilla/Effects/Voices/Asgore.ogg
  Resources/Audio/Vanilla/Effects/Voices/Asriel.ogg
  Resources/Audio/Vanilla/Effects/Voices/EvilFlowey.ogg
  Resources/Audio/Vanilla/Effects/Voices/Flowey.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania1.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania2.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania3.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania4.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania5.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania6.ogg
  Resources/Audio/Vanilla/Effects/Voices/Megalovania7.ogg
  Resources/Audio/Vanilla/Effects/Voices/Mettaton.ogg
  Resources/Audio/Vanilla/Effects/Voices/Papyrus.ogg
  Resources/Audio/Vanilla/Effects/Voices/SANS.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie1.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie2.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie3.ogg
  Resources/Audio/Vanilla/Effects/Voices/Temmie4.ogg
  Resources/Audio/Vanilla/Effects/Voices/Toriel.ogg
  Resources/Audio/Vanilla/Effects/Voices/Undyne.ogg
  Resources/Audio/Vanilla/Effects/Voices/Willow1.ogg
  Resources/Audio/Vanilla/Effects/Voices/Willow2.ogg
  Resources/Audio/Vanilla/Effects/Voices/Willow3.ogg
  Resources/Audio/Vanilla/Effects/Voices/Willow4.ogg
  Resources/Audio/Vanilla/Effects/Voices/Willow5.ogg
  Resources/Audio/Vanilla/Effects/Voices/Willow6.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany1.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany2.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany3.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany4.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany5.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany6.ogg
  Resources/Audio/Vanilla/Effects/Voices/walany7.ogg
  Resources/Audio/Vanilla/Effects/Voices/warly1.ogg
  Resources/Audio/Vanilla/Effects/Voices/warly2.ogg
  Resources/Audio/Vanilla/Effects/Voices/warly3.ogg
  Resources/Audio/Vanilla/Effects/Voices/warly4.ogg
  Resources/Audio/Vanilla/Effects/Voices/warly5.ogg
  Resources/Audio/Vanilla/Effects/Voices/wx1.ogg
  Resources/Audio/Vanilla/Effects/Voices/wx2.ogg
  Resources/Prototypes/Entities/Mobs/Customization/Markings/cat_parts.yml
  Resources/Prototypes/Vanilla/SoundCollections/Voices.yml
  Resources/Prototypes/Vanilla/Voices.yml
Labels: Changes: No C#, size/XS, Changes: Audio

#239 Фиксы ОБР
  Resources/Locale/ru-RU/vanilla/prototypes/eventteam/ERT.ftl
  Resources/Maps/Vanilla/Knocker_CBURN.yml
  Resources/Maps/Vanilla/Knocker_ERT_Base.yml
  Resources/Maps/Vanilla/Knocker_ERT_Base_Buffed.yml
  Resources/Maps/Vanilla/Knocker_ERT_Nukies.yml
  Resources/Maps/Vanilla/Knocker_ERT_Rev.yml
  Resources/Prototypes/Vanilla/EventTeam/Teams.yml
Labels: Changes: Map, Changes: Localization, Changes: No C#
