Repository RaytenCorp/Rayten, pull requests merged in 2025-05, with the labels that each got.

#245 Удешевление трекеров
  Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
Labels: Changes: No C#

#251 предстория
  Resources/Locale/ru-RU/vanilla/ui/background.ftl
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/XS

#252 initcommit
  Content.Client/Vanilla/Background/BackgroundPrototype.cs
  Content.Server/Vanilla/Background/BackgroundPrototype.cs
  Content.Shared/Vanilla/Background/Components/BackgroundComponent.cs
  Content.Shared/Vanilla/Background/Prototypes/BackgroundGroupPrototype.cs
  Content.Shared/Vanilla/Background/Prototypes/RoleBackground/RoleBackgroundPrototype.cs
  Content.Shared/Vanilla/Skill/components/SkillBookComponent.cs
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/salvage_specialist.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/Medical_doctor.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/chief_medical_officer.ftl
  Resources/Locale/ru-RU/vanilla/ui/background.ftl
  Resources/Prototypes/Entities/Objects/Misc/books.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Vanilla/Backgrounds/Cargo/salvage_specialist.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/chemist.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/chief_medical_officer.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/medical_doctor.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/LoneOpBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/NukeOpsTeam.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M

#254 qm and cargotech
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/cargo_technician.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/quartermaster.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/salvage_specialist.ftl
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Vanilla/Backgrounds/Cargo/cargo_technician.yml
  Resources/Prototypes/Vanilla/Backgrounds/Cargo/quartermaster.yml
Labels: Changes: Localization, Changes: No C#

#255 парамедик и интерн
  Content.Server/Antag/Components/AntagImmuneComponent.cs
  Content.Shared/Antag/AntagImmuneComponent.cs
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/Medical_doctor.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/Medical_intern.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/chief_medical_officer.ftl
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/medical_doctor.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/medical_intern.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/paramedic.yml
Labels: Changes: Localization, S: Untriaged, size/M

#262 Новые спортивные носки
  Resources/Locale/en-US/ss14-ru/prototypes/entities/clothing/under/under.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/under/under.ftl
  Resources/Prototypes/Entities/Clothing/Under/under.yml
  Resources/Textures/Clothing/Under/Socks/sporty.rsi/equipped-FEET-reptilian.png
  Resources/Textures/Clothing/Under/Socks/sporty.rsi/equipped-FEET.png
  Resources/Textures/Clothing/Under/Socks/sporty.rsi/icon.png
  Resources/Textures/Clothing/Under/Socks/sporty.rsi/meta.json
Labels: Changes: Localization, Changes: Sprites, Changes: No C#, S: Untriaged, size/S

#263 Бамгегло патчес
  Content.Shared/Vanilla/Coin/ReflectCoinComponent.cs
  Content.Shared/Vanilla/Coin/ReflectCoinSystem.cs
  Content.Shared/Vanilla/HealForDamage/HealForDamageComponent.cs
  Resources/Prototypes/Vanilla/Actions/Coins.yml
  Resources/Prototypes/Vanilla/Alerts/Alert.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/Silicon/silicon.yml
  Resources/Textures/Vanilla/Objects/Clothing/Head/Hardsuits/ERThelmets/peacekeeper.rsi/leader.png
  Resources/Textures/Vanilla/Objects/Clothing/Head/Hardsuits/ERThelmets/peacekeeper.rsi/med.png
  Resources/Textures/Vanilla/Objects/Clothing/Head/Hardsuits/ERThelmets/peacekeeper.rsi/off-equipped-HELMET.png
  Resources/Textures/Vanilla/Objects/Clothing/Head/Hardsuits/ERThelmets/peacekeeper.rsi/on-equipped-HELMET.png
  Resources/Textures/Vanilla/Objects/Clothing/OuterClothing/Hardsuits/ERTSuits/peacekeeper.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/OuterClothing/Hardsuits/ERTSuits/peacekeeper.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/OuterClothing/Hardsuits/ERTSuits/peacekeeper.rsi/leader.png
  Resources/Textures/Vanilla/Objects/Clothing/OuterClothing/Hardsuits/ERTSuits/peacekeeper.rsi/med.png
Labels: Changes: Sprites, size/S

#274 хост замерджи пж
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Vanilla/Actions/R1Actions.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/Silicon/silicon.yml
  Resources/Prototypes/Vanilla/EventTeam/ERTImplantedRoles.yml
  Resources/Prototypes/Vanilla/EventTeam/ERTSplodersRoles.yml
Labels: Changes: No C#, S: Untriaged, size/S
