Repository RaytenCorp/Rayten, pull requests merged in 2025-06, with the labels that each got.

#278 предыстория для скелетона и ядерного оперативника
  Content.Server/Vanilla/Background/misc/SkeletonCurse/SkeletonCurseComponent.cs
  Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
  Resources/Locale/ru-RU/lobby/lobby-gui.ftl
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Locale/ru-RU/vanilla/ghost/roles/cursedskeleton-component.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/ghostroles/NukeOpsTeam.ftl
  Resources/Locale/ru-RU/vanilla/tdm.ftl
  Resources/Prototypes/Catalog/Cargo/cargo_food.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
  Resources/Prototypes/Entities/Stations/nanotrasen.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/NukeOpsTeam.yml
  Resources/Prototypes/Vanilla/EventTeam/Teams.yml
  Resources/Prototypes/Vanilla/Roles/Antags/ghostroles/ClosetSkeleton.yml
  Resources/Prototypes/Vanilla/Roles/Antags/ghostroles/NukeOps.yml
  Resources/Prototypes/Vanilla/Roles/Antags/ghostroles/R1.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M

#279 склетные реворки
  Content.Server/Vanilla/Background/misc/SkeletonCurse/SkeletonCurseComponent.cs
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Polymorphs/polymorph.yml
Labels: S: Untriaged, size/S

#257 Фикс фелинидов 2
  Content.Shared/Vanilla/Felinid/Components/MobFelinidComponent.cs
  Content.Shared/Vanilla/Felinid/Systems/FelinidSpeedSystem.cs
  Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
  Resources/Prototypes/Vanilla/Felinid/felinid.yml
  Resources/Prototypes/Vanilla/Felinid/felinidsound/murchanie.ogg
  Resources/Prototypes/Vanilla/Felinid/felinidsound/myaukan.ogg
Labels: S: Untriaged, size/S, Changes: Audio

#282 Фикс Димедрола
  Resources/Prototypes/Recipes/Reactions/medicine.yml
Labels: Changes: No C#, S: Untriaged, S: Needs Review

#288 Правки в балансе бури
  Content.Server/Vanilla/GameTicking/Rules/Components/WhiteoutComponent.cs
  Content.Server/Vanilla/GameTicking/Rules/WhiteoutRuleSystem.cs
  Resources/Prototypes/Corvax/secret_weights.yml
  Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
  Resources/Prototypes/secret_weights.yml
Labels: S: Untriaged, size/S

#291 прокачка тдма
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Prototypes/Corvax/Entities/Objects/Misc/tiles.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/TDM/TDMBackgrounds.yml
  Resources/Prototypes/Vanilla/Roles/TDM_Gear.yml
  Resources/Prototypes/Vanilla/TDM_Arenas.yml
  Resources/Prototypes/game_presets.yml
Labels: Changes: No C#, size/M

#297 Фростпанк 1886
  Content.Server/Vanilla/GameTicking/Rules/Components/WhiteoutComponent.cs
  Content.Server/Vanilla/GameTicking/Rules/WhiteoutRuleSystem.cs
  Content.Server/Vanilla/Objectives/Components/EscapeLondonersConditionComponent.cs
  Content.Server/Vanilla/Objectives/Systems/EscapeLondonersConditionSystem.cs
  Content.Server/Vanilla/Roles/CanBeLondonerComponent.cs
  Content.Server/Vanilla/Roles/LondonerRoleComponent.cs
  Content.Server/Vanilla/Roles/R1RoleComponent.cs
  Resources/Audio/Vanilla/Ambience/Antag/Londoner.ogg
  Resources/Locale/ru-RU/vanilla/prototypes/roles/antags/londoner.ftl
  Resources/Maps/Vanilla/Misc/NewLondon.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/engivend.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/sec.yml
  Resources/Prototypes/Hydroponics/seeds.yml
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Tools/warmers.yml
  Resources/Prototypes/Vanilla/Gamerules/roundstart.yml
  Resources/Prototypes/Vanilla/Gamerules/whiteout.yml
  Resources/Prototypes/Vanilla/Hydroponics/seeds.yml
  Resources/Prototypes/Vanilla/Objectives/Londoner.yml
  Resources/Prototypes/Vanilla/Recipes/Cooking/Recipes.yml
  Resources/Prototypes/Vanilla/Roles/Antags/londoner.yml
  Resources/Prototypes/Vanilla/Roles/mind_roles.yml
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/activated.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/dead.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/harvest.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/produce-inhand-left.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/produce-inhand-right.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/produce.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/seed.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/stage-1.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/stage-2.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/stage-3.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/stage-4.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/stage-5.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/stage-6.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/unlit-produce-inhand-left.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/unlit-produce-inhand-right.png
  Resources/Textures/Vanilla/Objects/Specific/Hydroponics/warmchili.rsi/used.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/activated.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/inhand-left.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/inhand-right.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/spended.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/unlit-inhand-left.png
  Resources/Textures/Vanilla/Objects/Tools/HandWarmer.rsi/unlit-inhand-right.png
Labels: Changes: Map, Changes: Localization, Changes: Sprites, size/L, S: Untriaged, S: Needs Review, Changes: Audio

#304 разные приколы
  Resources/Locale/ru-RU/vanilla/prototypes/entities/weapons/guns/dominator_component.ftl
  Resources/Prototypes/Damage/modifier_sets.yml
  Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
  Resources/Prototypes/Entities/Mobs/Species/skeleton.yml
Labels: Changes: Localization, Changes: No C#, size/XS
