Repository RaytenCorp/Rayten, pull requests merged in 2025-07, with the labels that each got.

#307 Upstream sync
  Content.Client/Administration/UI/Logs/AdminLogsEui.cs
  Content.Server/Administration/Commands/DSay.cs
  Content.Server/Administration/Commands/DirtyCommand.cs
  Content.Server/Administration/Commands/FollowCommand.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.Processing.cs
  Content.Server/Explosion/EntitySystems/ExplosionSystem.cs
  Content.Server/Nuke/Commands/SendNukeCodesCommand.cs
  Content.Server/Power/Commands/PowerStatCommand.cs
  Content.Server/Remotes/DoorRemoteSystem.cs
  Content.Shared/Containers/ItemSlot/ItemSlotsSystem.cs
  Content.Shared/Remotes/Components/DoorRemoteComponent.cs
  Content.Shared/Storage/EntitySystems/BinSystem.cs
  Resources/Changelog/Admin.yml
  Resources/Changelog/Changelog.yml
  Resources/Credits/GitHub.txt
  Resources/Locale/en-US/administration/commands/dsay-command.ftl
  Resources/Locale/en-US/administration/commands/follow-command.ftl
  Resources/Locale/en-US/commands/dirty-command.ftl
  Resources/Locale/en-US/commands/dsay-command.ftl
  Resources/Locale/en-US/commands/follow-command.ftl
  Resources/Locale/en-US/commands/nukecodes-command.ftl
  Resources/Locale/en-US/commands/powerstat-command.ftl
  Resources/Locale/en-US/navmap-beacons/station-beacons.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/devices/door_remote.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/devices/station_beacon.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/vanilla/actions/R1Actions.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/vanilla/gamerules/roundstart.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/vanilla/roles/TDM_Gear.ftl
  Resources/Locale/en-US/vanilla/prototypes/entities/weapons/guns/dominator_component.ftl
  Resources/Locale/ru-RU/administration/commands/dsay-command.ftl
  Resources/Locale/ru-RU/administration/commands/follow-command.ftl
  Resources/Locale/ru-RU/cargo/cargo-bounty-console.ftl
  Resources/Locale/ru-RU/commands/dirty-command.ftl
  Resources/Locale/ru-RU/commands/dsay-command.ftl
  Resources/Locale/ru-RU/commands/follow-command.ftl
  Resources/Locale/ru-RU/commands/nukecodes-command.ftl
  Resources/Locale/ru-RU/commands/powerstat-command.ftl
  Resources/Locale/ru-RU/navmap-beacons/station-beacons.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/door_remote.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/station_beacon.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/actions/R1Actions.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/vanilla/roles/TDM_Gear.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Objects/Devices/door_remote.yml
  Resources/Prototypes/Entities/Objects/Devices/station_beacon.yml
  Resources/Prototypes/Vanilla/Roles/TDM_Gear.yml
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/base.png
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/icon.png
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/mag-unshaded-0.png
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/mag-unshaded-1.png
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/mag-unshaded-2.png
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/mag-unshaded-3.png
  Resources/Textures/Objects/Weapons/Guns/Battery/laser_retro.rsi/mag-unshaded-4.png
Labels: Changes: Localization, Changes: Sprites, S: Needs Review, size/M

#308 новые предыстории для скелетов
  Content.Shared/Vanilla/Background/misc/AngrySkeleton/AngrySkeletonComponent.cs
  Resources/Locale/ru-RU/nutrition/components/cream-pied-component.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.ftl
  Resources/Prototypes/Vanilla/Actions/ClosetSkeletonActions.yml
  Resources/Prototypes/Vanilla/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Roles/Antags/ghostroles/ClosetSkeleton.yml
Labels: Changes: Localization, S: Untriaged, S: Needs Review, size/M

#315 danger5
  Resources/Audio/Vanilla/StationEvents/attributions.yml
  Resources/Audio/Vanilla/StationEvents/grayalarm.ogg
  Resources/ConfigPresets/Vanilla/Base.toml
  Resources/Locale/en-US/alert-levels/alert-levels.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/objectives/traitor.ftl
  Resources/Locale/en-US/vanilla/ui/alertkey.ftl
  Resources/Locale/ru-RU/alert-levels/alert-levels.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/objectives/traitor.ftl
  Resources/Locale/ru-RU/vanilla/research/technologies.ftl
  Resources/Locale/ru-RU/vanilla/ui/alertkey.ftl
  Resources/Prototypes/AlertLevels/alert_levels.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
  Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
  Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
  Resources/Prototypes/Entities/Mobs/Player/guardian.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Objectives/objectiveGroups.yml
  Resources/Prototypes/Objectives/stealTargetGroups.yml
  Resources/Prototypes/Objectives/traitor.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Devices/AlertKeys.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Projectiles/hitscan.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Projectiles/projectiles.yml
  Resources/Prototypes/Vanilla/Recipes/Lathes/Packs/security.yml
  Resources/Prototypes/Vanilla/Recipes/Lathes/security.yml
  Resources/Prototypes/Vanilla/Research/arsenal.yml
  Resources/Prototypes/Vanilla/alertlevelreasons.yml
  Resources/ServerInfo/Guidebook/Security/Forensics.xml
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/base.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/equipped-BACK.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/inhand-right.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/mag-unshaded-0.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/mag-unshaded-1.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/mag-unshaded-2.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/mag-unshaded-3.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/mag-unshaded-4.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/unlit-lethal.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/unlit-safe.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/wielded-inhand-left.png
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/AssaultDominator.rsi/wielded-inhand-right.png
Labels: Changes: Localization, Changes: Sprites, Changes: No C#, S: Untriaged, S: Needs Review, size/M, Changes: Audio

#318 реворк предысторий и немного навыков
  Content.Server/Vanilla/Skill/Components/EmitSkillExperienceOnSpawnComponent.cs
  Content.Server/Vanilla/Skill/Components/GunTrainerComponent.cs
  Content.Server/Vanilla/Skill/Components/MeleeTrainerComponent.cs
  Content.Shared/Vanilla/Background/Prototypes/BackgroundGroupPrototype.cs
  Content.Shared/Vanilla/Background/Prototypes/RoleBackground/RoleBackgroundPrototype.cs
  Content.Shared/Vanilla/RoleSkills/RoleSkillsPrototype.cs
  Content.Shared/Vanilla/Skill/components/SkillLearnerComponent.cs
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/cargo_technician.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/quartermaster.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Cargo/salvage_specialist.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/Medical_doctor.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/Medical_intern.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Medical/chief_medical_officer.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Security/security_cadet.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/Backgrounds/Security/security_officer.ftl
  Resources/Prototypes/Entities/Clothing/Hands/gloves.yml
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Objects/Specific/Security/target.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/singularity.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/Tesla/energyball.yml
  Resources/Prototypes/Vanilla/Backgrounds/Cargo/cargo_technician.yml
  Resources/Prototypes/Vanilla/Backgrounds/Cargo/quartermaster.yml
  Resources/Prototypes/Vanilla/Backgrounds/Cargo/salvage_specialist.yml
  Resources/Prototypes/Vanilla/Backgrounds/ClosetSkeletonBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/LoneOpBackgrounds.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/chemist.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/chief_medical_officer.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/medical_doctor.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/medical_intern.yml
  Resources/Prototypes/Vanilla/Backgrounds/Medical/paramedic.yml
  Resources/Prototypes/Vanilla/Backgrounds/NukeOpsTeam.yml
  Resources/Prototypes/Vanilla/Backgrounds/Security/security_cadet.yml
  Resources/Prototypes/Vanilla/Backgrounds/Security/security_officer.yml
  Resources/Prototypes/Vanilla/Backgrounds/TDMBackgrounds.yml
  Resources/Prototypes/Vanilla/RoleSkills/civilian.yml
  Resources/Prototypes/Vanilla/RoleSkills/command.yml
  Resources/Prototypes/Vanilla/RoleSkills/engineering.yml
  Resources/Prototypes/Vanilla/RoleSkills/medical.yml
  Resources/Prototypes/Vanilla/RoleSkills/science.yml
  Resources/Prototypes/Vanilla/RoleSkills/security.yml
Labels: Changes: Localization, size/L, S: Needs Review

#317 Фигурачке
  Resources/Locale/ru-RU/datasets/figurines.ftl
  Resources/Locale/ru-RU/vanilla/datasets/figurines.ftl
  Resources/Locale/ru-RU/vanilla/station-events/events/r1-spawn.ftl
  Resources/Prototypes/Entities/Markers/Spawners/Random/toy.yml
  Resources/Prototypes/Vanilla/Datasets/figurines.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Fun/figurines.yml
  Resources/Textures/Vanilla/Objects/Fun/Figurines.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Fun/Figurines.rsi/r1.png
Labels: Changes: Localization, Changes: Sprites, Changes: No C#, S: Untriaged, size/M

#319 карта детектива теперь автокарта
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
Labels: Changes: No C#, S: Untriaged, S: Needs Review

#303 Атсос ребалансес
  Content.Client/Vanilla/Fluids/ClientBloodSuckerSystem.cs
  Content.Server/Vanilla/Atmos/EntitySystems/PressureExplosionSystem.cs
  Content.Server/Vanilla/GameTicking/Rules/WhiteoutRuleSystem.cs
  Content.Server/Vanilla/HealForDamage/HealForDamageSystem.cs
  Content.Server/Vanilla/Objectives/Systems/EscapeLondonersConditionSystem.cs
  Content.Server/Vanilla/Warmer/WarmerSystem.cs
  Content.Shared/Vanilla/Atmos/Components/PressureExplosionComponent.cs
  Content.Shared/Vanilla/Fluids/Components/BloodSuckerComponent.cs
  Content.Shared/Vanilla/Fluids/Systems/BloodSuckerSystem.cs
  Resources/Locale/ru-RU/datasets/figurines.ftl
  Resources/Locale/ru-RU/vanilla/recipes/tags.ftl
  Resources/Maps/centcomm.yml
  Resources/Maps/saltern.yml
  Resources/Prototypes/Atmospherics/gases.yml
  Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/pipes.yml
  Resources/Prototypes/Entities/Structures/Power/Generation/teg.yml
  Resources/Prototypes/Maps/centcomm.yml
  Resources/Prototypes/Maps/saltern.yml
  Resources/Prototypes/Recipes/Lathes/Packs/medical.yml
  Resources/Prototypes/Vanilla/Actions/Coins.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Player/Silicon/silicon.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Consumable/Food/Food.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Specific/Medical/bag.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Ammunitions/Projectiles/projectiles.yml
  Resources/Prototypes/Vanilla/Recipes/Construction/Graphs/fun.yml
  Resources/Prototypes/Vanilla/Recipes/Lathes/medical.yml
  Resources/Prototypes/Vanilla/tags.yml
  Resources/Textures/Vanilla/Actions/R1.rsi/Repair.png
  Resources/Textures/Vanilla/Actions/R1.rsi/Repair2.png
  Resources/Textures/Vanilla/Objects/Specific/Chemistry/bag.rsi/ephedronex.png
  Resources/Textures/Vanilla/Objects/Specific/Chemistry/bag.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Specific/Chemistry/bag.rsi/meta.json
Labels: Changes: Map, Changes: Localization, Changes: Sprites, size/XL, S: Untriaged, S: Needs Review

#310 Мэджишен
  Content.Server/Vanilla/Actions/ServerSploderSystem.cs
  Content.Server/Vanilla/GameTicking/Rules/WhiteoutRuleSystem.cs
  Content.Server/Vanilla/Objectives/Systems/EscapeLondonersConditionSystem.cs
  Content.Server/Vanilla/Warmer/WarmerSystem.cs
  Content.Shared/Vanilla/Actions/Components/SplodingComponent.cs
  Content.Shared/Vanilla/Actions/Events/SelfSplodingEvent.cs
  Content.Shared/Vanilla/Actions/Events/SplodeMarkingEvent.cs
  Resources/Audio/Vanilla/Effects/Actions/SelfSplodeCharge.ogg
  Resources/Audio/Vanilla/Effects/Actions/SplodeCharge.ogg
  Resources/Locale/ru-RU/vanilla/actions/actions.ftl
  Resources/Prototypes/Vanilla/Actions/Magic.yml
  Resources/Prototypes/Vanilla/Actions/types.yml
  Resources/Prototypes/Vanilla/Catalog/spellbook_catalog.yml
  Resources/Prototypes/Vanilla/explosion.yml
  Resources/Textures/Vanilla/Actions/Splode.rsi/ItemSplode.png
  Resources/Textures/Vanilla/Actions/Splode.rsi/SelfCharge.png
  Resources/Textures/Vanilla/Actions/Splode.rsi/meta.json
Labels: Changes: Map, Changes: Localization, Changes: Sprites, S: Untriaged, size/M, Changes: Audio

#325 vox update
  Resources/ConfigPresets/Vanilla/Aegis.toml
  Resources/ConfigPresets/Vanilla/Base.toml
  Resources/ConfigPresets/Vanilla/Master.toml
  Resources/Locale/ru-RU/datasets/names/vox.ftl
  Resources/Prototypes/Entities/Mobs/Species/vox.yml
  Resources/Prototypes/GameRules/events.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Science/research_director.yml
  Resources/Prototypes/Roles/Jobs/Security/detective.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: Changes: Localization, Changes: No C#, S: Needs Review, size/M

#328 различные поросячие звуки скачать онлайн
  Resources/Audio/Vanilla/Effects/Gasp/attributions.yml
  Resources/Audio/Vanilla/Effects/Gasp/trottine_deathgasp_1.ogg
  Resources/Audio/Vanilla/Effects/Gasp/trottine_deathgasp_2.ogg
  Resources/Audio/Vanilla/Effects/Gasp/trottine_deathgasp_3.ogg
  Resources/Audio/Vanilla/Effects/Gasp/trottine_deathgasp_4.ogg
  Resources/Audio/Vanilla/Voice/Trottine/attributions.yml
  Resources/Audio/Vanilla/Voice/Trottine/trottine_crying.ogg
  Resources/Audio/Vanilla/Voice/Trottine/trottine_grunt.ogg
  Resources/Audio/Vanilla/Voice/Trottine/trottine_laugh.ogg
  Resources/Audio/Vanilla/Voice/Trottine/trottine_scream.ogg
  Resources/Audio/Vanilla/Voice/Trottine/trottine_sigh.ogg
  Resources/Locale/ru-RU/vanilla/chat/chat.ftl
  Resources/Locale/ru-RU/vanilla/chat/emotes.ftl
  Resources/Prototypes/Vanilla/Entities/Mobs/Species/trottines.yml
  Resources/Prototypes/Vanilla/SoundCollections/deathgasp.yml
  Resources/Prototypes/Vanilla/Voice/speech_emote_sounds.yml
  Resources/Prototypes/Vanilla/Voice/speech_emotes.yml
  Resources/Textures/Vanilla/Interface/Emotes/attributions.yml
  Resources/Textures/Vanilla/Interface/Emotes/grunt.png
Labels: Changes: Localization, Changes: No C#, size/S, Changes: Audio

#329 Скрелачеке
  Content.Shared/Humanoid/NamingSystem.cs
  Content.Shared/Humanoid/Prototypes/SpeciesPrototype.cs
  Resources/Locale/en-US/vanilla/datasets/names/skrell-names.ftl
  Resources/Locale/en-US/vanilla/species/namepreset.ftl
  Resources/Locale/ru-RU/vanilla/chemistry/metabolizer-types.ftl
  Resources/Locale/ru-RU/vanilla/datasets/names/skrell-names.ftl
  Resources/Locale/ru-RU/vanilla/markings/skrell.ftl
  Resources/Locale/ru-RU/vanilla/species/namepreset.ftl
  Resources/Prototypes/Reagents/Consumable/Drink/alcohol.yml
  Resources/Prototypes/Reagents/Consumable/Drink/drinks.yml
  Resources/Prototypes/Reagents/Consumable/Food/food.yml
  Resources/Prototypes/Reagents/biological.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Vanilla/Body/Organs/skrell.yml
  Resources/Prototypes/Vanilla/Body/Parts/skrell.yml
  Resources/Prototypes/Vanilla/Body/Prototypes/skrell.yml
  Resources/Prototypes/Vanilla/Chemistry/metabolizer_types.yml
  Resources/Prototypes/Vanilla/Damage/modifier_sets.yml
  Resources/Prototypes/Vanilla/Datasets/skrell-names.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Customization/Markings/skrell_hair.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/Species/skrells.yml
  Resources/Prototypes/Vanilla/Species/skrell.yml
  Resources/Textures/Vanilla/Mobs/Customization/skrell_hair.rsi/Short.png
  Resources/Textures/Vanilla/Mobs/Customization/skrell_hair.rsi/Snips.png
  Resources/Textures/Vanilla/Mobs/Customization/skrell_hair.rsi/ThreeTails.png
  Resources/Textures/Vanilla/Mobs/Customization/skrell_hair.rsi/meta.json
  Resources/Textures/Vanilla/Mobs/Species/Skrell/displacement.rsi/jumpsuit-female.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/displacement.rsi/meta.json
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/full.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/head_f.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/head_m.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/l_arm.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/l_foot.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/l_hand.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/l_leg.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/meta.json
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/r_arm.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/r_foot.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/r_hand.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/r_leg.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/torso_f.png
  Resources/Textures/Vanilla/Mobs/Species/Skrell/parts.rsi/torso_m.png
  Resources/Textures/Vanilla/Mobs/Species/Trottine/parts.rsi/head_f.png
  Resources/Textures/Vanilla/Mobs/Species/Trottine/parts.rsi/torso_f.png
Labels: Changes: Localization, Changes: Sprites, Changes: No C#, S: Needs Review, size/M
