Repository RaytenCorp/Rayten, pull requests merged in 2025-02, with the labels that each got.

#151 Upstream sync
  Resources/Audio/Corvax/Lobby/NewYear/attributions.yml
  Resources/Audio/Corvax/Lobby/NewYear/carol-of-the-bells.ogg
  Resources/Audio/Corvax/Lobby/NewYear/dance-of-sugar-plum-fairy.ogg
  Resources/Audio/Corvax/Lobby/NewYear/deck-in-the-halls.ogg
  Resources/Audio/Corvax/Lobby/NewYear/jingle-bells.ogg
  Resources/Audio/Corvax/Lobby/NewYear/wish-you-a-merry-christmas.ogg
  Resources/Locale/ru-RU/cargo/cargo-console-component.ftl
  Resources/Locale/ru-RU/holopad/holopad.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/holopad.ftl
  Resources/Maps/Corvax/corvax_pearl.yml
  Resources/Prototypes/Corvax/Lathes/misc.yml
  Resources/Prototypes/SoundCollections/lobby.yml
  Resources/Textures/Interface/Actions/actions_mecha.rsi/mech_eject.png
  Resources/Textures/Interface/Actions/actions_mecha.rsi/mech_ivanov_cooldown.png
  Resources/Textures/Interface/Actions/actions_mecha.rsi/mech_savannah_cooldown.png
  Resources/Textures/Interface/Actions/actions_mecha.rsi/mech_view_stats.png
  Resources/Textures/Interface/Actions/actions_mecha.rsi/meta.json
  Resources/Textures/Interface/Alerts/Buckle/buckled.png
  Resources/Textures/Interface/Alerts/Handcuffed/Handcuffed.png
  Resources/Textures/Interface/Alerts/Pull/pulled.png
  Resources/Textures/Interface/Alerts/breathing.rsi/meta.json
  Resources/Textures/Interface/Alerts/breathing.rsi/not_enough_tox.png
  Resources/Textures/Interface/Alerts/breathing.rsi/too_much_tox.png
  Resources/Textures/Interface/Alerts/ensnared.rsi/ensnared.png
  Resources/Textures/Interface/Alerts/ensnared.rsi/meta.json
Labels: Changes: Map, Changes: Localization, Changes: Sprites, size/L, Changes: No C#, S: Untriaged, Changes: Audio

#150 добавлено больше документов
  Resources/Locale/en-US/ss14-ru/prototypes/corvax/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/corvax/entities/objects/misc/flatpacks.ftl
  Resources/Locale/en-US/ss14-ru/prototypes/corvax/entities/structures/machines/printer.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/entities/objects/devices/circuitboards/machine/production.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/entities/objects/misc/flatpacks.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/entities/structures/machines/printer.ftl
  Resources/Locale/ru-RU/vanilla/Bureaucracy/Orders.ftl
  Resources/Locale/ru-RU/vanilla/Bureaucracy/Reports.ftl
  Resources/Locale/ru-RU/vanilla/Bureaucracy/Requests.ftl
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/curadrobe.yml
  Resources/Prototypes/Corvax/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/Corvax/Entities/Objects/Misc/flatpacks.yml
  Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
  Resources/Prototypes/Corvax/Lathes/misc.yml
  Resources/Prototypes/Corvax/Recipes/Lathes/printer.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/SoundCollections/NukeMusic.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Reports.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Requests.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/orders.yml
  Resources/migration.yml
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/M

#152 ALARM!!
  Content.Client/Vanilla/AlertKey/AlertKeyBoundUserInterface.cs
  Content.Client/Vanilla/AlertKey/AlertKeyMenu.xaml
  Content.Client/Vanilla/AlertKey/AlertKeyMenu.xaml.cs
  Content.Server/Vanilla/entities/AlertKey/AlertKeyComponent.cs
  Content.Server/Vanilla/entities/MemoryShield/MemoryShieldComponent.cs
  Content.Shared/Vanilla/AlertKey/SharedAlertKeyComponent.cs
  Resources/Audio/Vanilla/StationEvents/attributions.yml
  Resources/Audio/Vanilla/StationEvents/grayalarm.ogg
  Resources/Locale/ru-RU/alert-levels/alert-levels.ftl
  Resources/Locale/ru-RU/light/components/emergency-light-component.ftl
  Resources/Locale/ru-RU/pda/pda-component.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/Devices/AlertKey.ftl
  Resources/Prototypes/Vanilla/DepartmentGoals/SecGoals.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Devices/AlertKeys.yml
  Resources/Textures/Vanilla/Interface/VerbIcons/pen.svg
  Resources/Textures/Vanilla/Interface/VerbIcons/pen.svg.192dpi.png
  Resources/Textures/Vanilla/Interface/VerbIcons/pen.svg.192dpi.png.yml
  Resources/Textures/Vanilla/Objects/Devices/alert_key.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Devices/alert_key.rsi/red.png
  Resources/Textures/Vanilla/Objects/Devices/alert_key.rsi/universal.png
  Resources/Textures/Vanilla/Objects/Devices/alert_key.rsi/violet.png
  Resources/Textures/Vanilla/Objects/Devices/alert_key.rsi/yellow.png
Labels: Changes: Localization, Changes: Sprites, Changes: UI, S: Untriaged, size/M, Changes: Audio

#153 Добавлен шаттл ПЦК
  Resources/Maps/Vanilla/CCOfficial_Shuttle.yml
Labels: Changes: Map, size/L, Changes: No C#, S: Untriaged

#157 ребаланс времени в лобби и в ендгейме
  Resources/ConfigPresets/Vanilla/Vanilla.toml
Labels: Changes: No C#, S: Untriaged

#162 nukeupdate
  Content.Server/GameTicking/Rules/Components/NukeopsRuleComponent.cs
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/Devices/nukedisc.ftl
  Resources/Prototypes/Entities/Objects/Misc/dat_fukken_disk.yml
  Resources/Prototypes/Roles/Antags/nukeops.yml
Labels: Changes: Localization, S: Untriaged

#163 возвращена дискорд-авторизация
  Resources/Locale/ru-RU/vanilla/discord-auth.ftl
Labels: Changes: Localization, Changes: No C#, S: Untriaged, size/XS
