Repository RaytenCorp/Rayten, pull requests merged in 2025-01, with the labels that each got.

#114 AMNESIA
  Content.Server/Mindshield/MindShieldSystem.cs
  Content.Server/Vanilla/MemoryShield/MemoryShieldComponent.cs
  Content.Server/Vanilla/Skill/Components/AddSkillPointsComponent.cs
  Content.Server/Vanilla/Skill/Components/GunCanBeFallComponent.cs
  Content.Server/Vanilla/Skill/Components/GunIgnoreSkillComponent.cs
  Content.Server/Vanilla/Skill/Components/GunTrainerComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillAmesiaComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillTrainerComponent.cs
  Content.Shared/Vanilla/Skill/components/gun/GunTrainerComponent.cs
  Content.Shared/Vanilla/Skill/components/gun/UnSkilledGunComponent.cs
  Resources/Audio/Vanilla/Lobby/Concrete.ogg
  Resources/Audio/Vanilla/Lobby/attributions.yml
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/implants/implanters.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/objects/implants/subdermal_implants.ftl
  Resources/Locale/ru-RU/vanilla/research/technologies.ftl
  Resources/Prototypes/Entities/Objects/Misc/books.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Prototypes/SoundCollections/lobby.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Misc/implanters.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Misc/subdermal_implants.yml
  Resources/Prototypes/Vanilla/Recipes/Lathes/Robotics.yml
  Resources/Prototypes/Vanilla/Research/arsenal.yml
  Resources/Prototypes/tags.yml
Labels: Changes: Localization, S: Untriaged, size/M, Changes: Audio

#116 meleeweapon
  Content.Server/Vanilla/Skill/Components/GunTrainerComponent.cs
  Resources/Changelog/ChangelogVanilla.yml
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Security/warden.yml
Labels: S: Untriaged, size/S

#117 Rules update
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/janitor.yml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/MrpRuleset.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule0.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule1.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule11.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule12.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule13.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule14.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule15.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule16.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule2.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule3.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule31.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule6.xml
  Resources/ServerInfo/Vanilla/Guidebook/ServerRules/Rule61.xml
Labels: Changes: No C#, S: Untriaged

#120 somefixes
  Resources/Changelog/ChangelogVanilla.yml
  Resources/Prototypes/Corvax/Roles/Jobs/Security/pilot.yml
  Resources/Prototypes/Entities/Clothing/Ears/headsets.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
Labels: Changes: No C#, S: Untriaged

#121 Мелкий респрайт
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/equipped-HELMET-hamster.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/equipped-HELMET.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/cap.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/coat.rsi/icon.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/Vanilla/Objects/Clothing/Naval_Captain/jumpsuit.rsi/icon.png
Labels: Changes: Sprites, Changes: No C#, S: Untriaged, size/XS

#123 Очень мелкие фиксы
  Content.Shared/CCVar/CCVars.Chat.cs
  Resources/ConfigPresets/Vanilla/Vanilla.toml
  Resources/Maps/Shuttles/ShuttleEvent/cookers_shuttle.yml
Labels: Changes: Map, size/M

#124 Цвета для ООС и ахелпов
  Content.Server/Administration/Systems/BwoinkSystem.cs
  Content.Server/Chat/Managers/ChatManager.cs
  Resources/Locale/ru-RU/vanilla/chat.ftl
  Resources/Prototypes/Corvax/Maps/cuteinstallation.yml
Labels: Changes: Map, Changes: Localization, size/S

#127 авточенжлог
  .github/workflows/publish.yml
  Tools/actions_changelog_rss.py
Labels: Changes: No C#, size/S

#128 autochangelog
  Tools/actions_changelogs_since_last_run.py
Labels: Changes: No C#, S: Untriaged, size/XS

#130 боже мой...
  Tools/actions_changelogs_since_last_run.py
Labels: Changes: No C#, S: Untriaged, size/XS

#132 FootprintsRework
  Content.Client/_CorvaxNext/Footprints/FootprintSystem.cs
  Content.Server/Chemistry/TileReactions/CleanTileReaction.cs
  Content.Server/Fluids/EntitySystems/AbsorbentSystem.cs
  Content.Server/Fluids/EntitySystems/PuddleSystem.cs
  Content.Server/_CorvaxNext/Footprints/FootprintCleanEvent.cs
  Content.Server/_CorvaxNext/Footprints/FootprintOwnerComponent.cs
  Content.Server/_CorvaxNext/Footprints/FootprintSystem.cs
  Content.Shared/Fluids/Components/PuddleComponent.cs
  Content.Shared/Fluids/SharedPuddleSystem.cs
  Content.Shared/_CorvaxNext/Footprints/FootprintChangedEvent.cs
  Content.Shared/_CorvaxNext/Footprints/FootprintComponent.cs
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/effects/footprint.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/effects/footstep.ftl
  Resources/Prototypes/Entities/Mobs/Species/base.yml
  Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
  Resources/Prototypes/_CorvaxNext/Entities/Effects/footprint.yml
  Resources/Textures/_CorvaxNext/Effects/footprint.rsi/body.png
  Resources/Textures/_CorvaxNext/Effects/footprint.rsi/foot.png
  Resources/Textures/_CorvaxNext/Effects/footprint.rsi/meta.json
Labels: Changes: Localization, Changes: Sprites, S: Untriaged, size/M

#136 ezmode vote final version
  Resources/Locale/ru-RU/vanilla/Skill-system.ftl
Labels: Changes: Localization, Changes: No C#, size/XS

#137 Skillsrework
  Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
  Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
  Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Labels: S: Untriaged, size/S

#139 yay release version of skill system
  Content.Server/Vanilla/Skill/Components/GunCanBeFallComponent.cs
  Content.Server/Vanilla/Skill/Components/MeleeTrainerComponent.cs
  Content.Shared/Construction/Prototypes/ConstructionPrototype.cs
  Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillComponent.cs
  Content.Shared/Vanilla/Skill/components/SkillLearnerComponent.cs
  Resources/Prototypes/Entities/Mobs/Species/base.yml
Labels: S: Untriaged, size/M

#140 depgoalsystemhi
  Content.Client/Entry/EntryPoint.cs
  Content.Server/Corvax/StationGoal/StationGoalCommand.cs
  Content.Server/Corvax/StationGoal/StationGoalPaperSystem.cs
  Content.Server/Vanilla/DepartmentGoal/DepartmentGoalPrototype.cs
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/CargoGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/EngGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/MedGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/RnDGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/SecGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/SrvGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/base.ftl
  Resources/Prototypes/Vanilla/DepartmentGoals/CargoGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/EngGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/MedGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/RnDGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SecGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SrvGoals.yml
Labels: Changes: Localization, S: Untriaged, size/M

#141 goal benefits
  Content.Server/Vanilla/DepartmentGoal/DepartmentGoalPrototype.cs
  Content.Shared/Lock/LockComponent.cs
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/GoalsAnnounce.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/base.ftl
  Resources/Prototypes/Vanilla/DepartmentGoals/CargoGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/EngGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/MedGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/RnDGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SecGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SrvGoals.yml
  Resources/Prototypes/Vanilla/Entities/crates/benefitcrates.yml
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/base.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/closed.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/icon.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/locked.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/meta.json
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/open.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/sparking.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/unlocked.png
  Resources/Textures/Vanilla/Structures/Storage/Crates/benefitcrate.rsi/welded.png
Labels: Changes: Localization, Changes: Sprites, S: Untriaged, size/M

#142 somefixes
  Content.Server/KillTracking/KillTrackerComponent.cs
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/CargoGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/EngGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/MedGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/SecGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/SrvGoals.ftl
  Resources/Locale/ru-RU/vanilla/DepartmentGoals/base.ftl
  Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/CargoGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/EngGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/MedGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/RnDGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SecGoals.yml
  Resources/Prototypes/Vanilla/DepartmentGoals/SrvGoals.yml
  Resources/Prototypes/Vanilla/Entities/crates/benefitcrates.yml
Labels: Changes: Localization, S: Untriaged, size/M

#145 dmca moment
  Content.Client/_CorvaxNext/Footprints/FootprintSystem.cs
  Content.Server/_CorvaxNext/Footprints/FootprintCleanEvent.cs
  Content.Server/_CorvaxNext/Footprints/FootprintOwnerComponent.cs
  Content.Server/_CorvaxNext/Footprints/FootprintSystem.cs
  Content.Shared/_CorvaxNext/Footprints/FootprintChangedEvent.cs
  Content.Shared/_CorvaxNext/Footprints/FootprintComponent.cs
  README.md
Labels: S: Untriaged, size/M

#147 Upstream sync
  Resources/Audio/Vanilla/StationEvents/attributions.yml
  Resources/Maps/Corvax/Shuttles/emergency_corvaxcute.yml
  Resources/Maps/Corvax/corvax_cute.yml
  Resources/Maps/Corvax/corvax_maus.yml
  Resources/Textures/Logo/logo-ru-tape.png
Labels: Changes: Map, Changes: No C#, size/XL, S: Untriaged

#148 Buro
  Content.Shared/Vanilla/Bureaucracy/BureaucracyDocumentPrototype.cs
  Content.Shared/Vanilla/Bureaucracy/BureaucracyPenComponent.cs
  Content.Shared/Verbs/VerbCategory.cs
  Resources/Locale/ru-RU/vanilla/Bureaucracy/Orders.ftl
  Resources/Locale/ru-RU/vanilla/Bureaucracy/Reports.ftl
  Resources/Locale/ru-RU/vanilla/Bureaucracy/Requests.ftl
  Resources/Locale/ru-RU/vanilla/Bureaucracy/base.ftl
  Resources/Prototypes/Entities/Objects/Misc/pen.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Reports.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Requests.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/Template.yml
  Resources/Prototypes/Vanilla/BureaucracyDocuments/orders.yml
Labels: Changes: Localization, S: Untriaged, size/M
