Repository RaytenCorp/Rayten, pull requests merged in 2025-09, with the labels that each got.

#351 доминаторские фиксы
  Resources/Prototypes/Entities/Mobs/NPCs/elemental.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/cult.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Labels: Changes: No C#, S: Untriaged, size/S

#342 Косрикческая Станция 14
  Content.Server/Vanilla/Teleportation/PortalGunSystem.cs
  Content.Server/Vanilla/Teleportation/PortalMapCleanerSystem.cs
  Content.Server/Vanilla/Teleportation/RandomPortalSystem.cs
  Content.Shared/Vanilla/Teleportation/Components/PortalGunComponent.cs
  Content.Shared/Vanilla/Teleportation/Components/PortalMapComponent.cs
  Content.Shared/Vanilla/Teleportation/Components/RandomPortalComponent.cs
  Resources/Audio/Vanilla/Effects/randomPortal.ogg
  Resources/Audio/Vanilla/Effects/randomPortalOmega.ogg
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/chemicals.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/physical-desc.ftl
  Resources/Locale/en-US/vanilla/recipes/tags.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/reagents/meta/chemicals.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/reagents/meta/physical-desc.ftl
  Resources/Locale/ru-RU/vanilla/recipes/tags.ftl
  Resources/Prototypes/Entities/Objects/Devices/hand_teleporter.yml
  Resources/Prototypes/Vanilla/Entities/Effects/portal.yml
  Resources/Prototypes/Vanilla/Entities/Markers/Spawners/Mobs/hostile.yml
  Resources/Prototypes/Vanilla/Entities/Markers/Spawners/misc.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Misc/plumbus.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Misc/ultraseed.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Battery/portalgun.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Projectiles/projectiles.yml
  Resources/Prototypes/Vanilla/Entities/Structures/Misc/ttt_decorations.yml
  Resources/Prototypes/Vanilla/Procedural/biome_templates.yml
  Resources/Prototypes/Vanilla/Reagents/portal_juice.yml
  Resources/Prototypes/Vanilla/Recipes/Crafting/Graphs/misc/gorgeousPortalgun.yml
  Resources/Prototypes/Vanilla/Recipes/Crafting/Graphs/misc/makeshiftPortalgun.yml
  Resources/Prototypes/Vanilla/Recipes/Crafting/Graphs/misc/portalgun.yml
  Resources/Prototypes/Vanilla/Recipes/Crafting/misc.yml
  Resources/Prototypes/Vanilla/Recipes/Reactions/PortalJuice.yml
  Resources/Prototypes/Vanilla/tags.yml
  Resources/Textures/Vanilla/Effects/portal.rsi/green.png
  Resources/Textures/Vanilla/Effects/portal.rsi/meta.json
  Resources/Textures/Vanilla/Effects/portal.rsi/yellow.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/base.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/fill1.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/fill2.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/fill3.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/fill4.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/fill5.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/fill6.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgeous.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgfill1.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgfill2.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgfill3.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgfill4.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgfill5.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/gorgfill6.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/makeshift.png
  Resources/Textures/Vanilla/Objects/Devices/portal_gun.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Misc/plumbus.rsi/base.png
  Resources/Textures/Vanilla/Objects/Misc/plumbus.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Misc/ultraseed.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Misc/ultraseed.rsi/tree.png
  Resources/Textures/Vanilla/Objects/Misc/ultraseed.rsi/ultraseed.png
Labels: Changes: Localization, Changes: Sprites, size/L, S: Untriaged, S: Needs Review, Changes: Audio

#357 Newitems
  Resources/Prototypes/Vanilla/Entities/Clothing/Back/backpacks.yml
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/equipped-BACKPACK.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/holding-broken-equipped-BACKPACK.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/holding-broken.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/holding-equipped-BACKPACK.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/holding-unlit.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/holding.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/icon.png
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/meta.json
  Resources/Textures/Vanilla/Clothing/Back/Backpacks/absolutepack.rsi/unlit.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/doublestunbaton.rsi/equipped-BACKPACK.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/doublestunbaton.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/Vanilla/Objects/Weapons/Melee/doublestunbaton.rsi/meta.json
Labels: Changes: Sprites, Changes: No C#, S: Untriaged, S: Needs Review, size/S

#359 newchems
  Content.Shared/Vanilla/Entities/BrainWorm/BrainWormEvents.cs
  Content.Shared/Vanilla/Entities/BrainWorm/Components/BrainWormComponent.cs
  Content.Shared/Vanilla/Entities/BrainWorm/Components/BrainWormHostComponent.cs
  Content.Shared/Vanilla/Entities/BrainWorm/Components/UnderControlComponent.cs
  Content.Shared/Vanilla/EntityEffects/Effects/DamageBrainWorm.cs
  Resources/Locale/en-US/vanilla/headset/headset-component.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/chemicals.ftl
  Resources/Locale/en-US/vanilla/prototypes/reagents/meta/physical-desc.ftl
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Vanilla/Catalog/brainworm_catalog.yml
  Resources/Prototypes/Vanilla/Entities/Mobs/NPCs/BrainWorm.yml
  Resources/Prototypes/Vanilla/Gamerules/pests.yml
  Resources/Prototypes/Vanilla/Reagents/chemicals.yml
  Resources/Prototypes/Vanilla/StatusIcon/StatusEffects/brainworm.yml
  Resources/Prototypes/Vanilla/Store/categories.yml
  Resources/Prototypes/Vanilla/Store/currency.yml
  Resources/Prototypes/Vanilla/radio_channels.yml
  Resources/Textures/Vanilla/Clothing/Eyes/Hud/night_vision_device.rsi/meta.json
  Resources/Textures/Vanilla/Interface/Actions/brainworm.rsi/ejectbrain.png
  Resources/Textures/Vanilla/Interface/Actions/brainworm.rsi/insertbrain.png
  Resources/Textures/Vanilla/Interface/Actions/brainworm.rsi/meta.json
  Resources/Textures/Vanilla/Interface/Actions/brainworm.rsi/mindcontrol.png
  Resources/Textures/Vanilla/Interface/Actions/brainworm.rsi/returncontrol.png
  Resources/Textures/Vanilla/Interface/Misc/damage_group_icons.rsi/brainworm.png
  Resources/Textures/Vanilla/Interface/Misc/damage_group_icons.rsi/meta.json
  Resources/Textures/Vanilla/Mobs/Animals/brainworm.rsi/brainworm.png
  Resources/Textures/Vanilla/Mobs/Animals/brainworm.rsi/brainworm_dead.png
  Resources/Textures/Vanilla/Mobs/Animals/brainworm.rsi/brainworm_icon.png
  Resources/Textures/Vanilla/Mobs/Animals/brainworm.rsi/meta.json
  Resources/Textures/Vanilla/Objects/Weapons/Guns/Battery/Dominator.rsi/meta.json
Labels: Changes: Localization, Changes: Sprites, S: Untriaged, S: Needs Review, size/M

#363 червяк и доминатор
  Content.Shared/Vanilla/Entities/BrainWorm/Components/BrainWormComponent.cs
  Content.Shared/Vanilla/Entities/Dominator/DominatorComponent.cs
  Resources/Locale/en-US/vanilla/datasets/dominator.ftl
  Resources/Locale/en-US/vanilla/prototypes/entities/BrainWormComponent.ftl
  Resources/Locale/en-US/vanilla/station-laws/laws.ftl
  Resources/Locale/ru-RU/chemistry/solution/components/shared-solution-container-component.ftl
  Resources/Locale/ru-RU/vanilla/datasets/dominator.ftl
  Resources/Locale/ru-RU/vanilla/prototypes/entities/BrainWormComponent.ftl
  Resources/Locale/ru-RU/vanilla/station-laws/laws.ftl
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Reagents/Consumable/Food/food.yml
  Resources/Prototypes/Reagents/medicine.yml
  Resources/Prototypes/Vanilla/Datasets/dominator.yml
  Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
  Resources/Prototypes/Vanilla/Reagents/chemicals.yml
  Resources/Prototypes/Vanilla/silicon-laws.yml
Labels: Changes: Localization, S: Untriaged, S: Needs Review, size/M

#364 [Maps][hotfix] Fix maps for tdm
  Resources/Maps/Vanilla/Misc/TTT/TTT_Mine.yml
  Resources/Maps/Vanilla/Misc/TTT/TTT_RickAndMorty.yml
  Resources/Prototypes/Vanilla/TDM_Arenas.yml
Labels: Changes: Map, Changes: No C#, S: Untriaged, S: Needs Review
